### ISSUE TITLE
Card component does not allow Cypress to click element

### ISSUE THREAD

**Issue by david-mcafee** [aws-amplify/amplify-ui#2370] opened 2022-07-29 00:59 UTC
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Other

### How is your app built?

Create react app

### What browsers are you seeing the problem on?

Chrome

### Please describe your bug.

Cypress tests fail to select html buttons nested in Amplify UI components. The workaround is to set a high z-index for the buttons.

### What's the expected behaviour?

Cypress tests would be able to select html buttons nested in Amplify UI components.

### Help us reproduce the bug!

Nest an HTML button inside a Card component, and attempt to click the button using Cypress.

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by jacoblogan** [comment] 2022-07-29 15:15
Hi @david-mcafee,  Thank you for opening this issue.  I'm unable to reproduce the issue, do you have a code snippet of a minimal example that you could share? Also can you share your cypress test that is failing?

**Comment by Milan-Shah** [comment] 2022-09-30 14:16
@david-mcafee , We have been unable to reproduce this issue, does not mean that issue doesnt exist. Please provide us more details about your cypress test, we have tried testing a nested html button inside a card component and it works as expected. 

Closing this issue for now, please feel free to reopen if you are still having problems with your cypress test.

**Closed by Milan-Shah** 2022-09-30 14:16 UTC
Labels: pending-response, React, Primitive
