### ISSUE TITLE
control the country code for phone sign in

### ISSUE THREAD

**Issue by AsemK** [aws-amplify/amplify-ui#914] opened 2021-11-30 22:17 UTC
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

I have an app that allows users to sign up with phone numbers only from a number of countries. I would like to be able to control the country code choices in the sign-in tab such that they can be only a subset of countries or that it is only one country and cannot be changed.

### Please describe a solution you'd like.

several options:
- add a prop for that.
- allow an easy way to replace the field with another custom component.

**Comment by jerocosio** [comment] 2021-11-30 22:59
I was able to do this before with AmplifySignUp and adding the info as a `formField`, but I haven't figured out the right way to do so with the new UI, before it worked like this:

```
<AmplifySignUp
          headerText=""
          slot="sign-up"
          usernameAlias="email"
          formFields={[
            {
              type: "phone_number",
              label: "Teléfono celular *",
              placeholder: "10 dígitos, enviaremos un SMS para confirmar",
              required: true,
              dialCode: "+52",
              hint: "Enviaremos un SMS para confirmar.",
            },
          ]}
        />
```

**Comment by jerocosio** [comment] 2021-11-30 23:03
Also, it looks like this is a duplicate of: https://github.com/aws-amplify/amplify-ui/issues/821

**Comment by AsemK** [comment] 2021-11-30 23:24
No. The other issue talks about the default country code. Here, I am talking about controlling the choices.

**Comment by ErikCH** [comment] 2021-12-01 20:02
Hi @AsemK !

Right now there is no way to directly change the country code with a prop. However, we do have a way to customize the sign up page. 

https://ui.docs.amplify.aws/components/authenticator#sign-up-fields

You could create your own `phone_number` field with your own select drop down. And then add in your own password fields too. Would something like this work for you?

I'll mark this as a feature request for the future.

**Comment by AsemK** [comment] 2021-12-01 20:07
Thanks for your reply @ErikCH. Unfortunately, this will not work because I need to customize the sign-in page also. My understanding is this is not available until now.

**Comment by ErikCH** [comment] 2021-12-01 20:54
Hi @AsemK ! 

Yes, you are right. We'll see what we can do to add this in the future!

**Comment by gomesp** [comment] 2021-12-03 01:58
Hey @jerocosio, yes it is exactly the behaviour I wanted when I raised #821

**Comment by ErikCH** [comment] 2022-03-01 21:34
Hi @AsemK !

I implemented this feature with a new `dialCodeList` key under `formFields` prop. It will be released today. Please take a look at the documentation https://ui.docs.amplify.aws/components/authenticator#form-field-customization

Please open a bug if you run into any issues.

**Closed by ErikCH** 2022-03-01 21:34 UTC
Labels: feature-request, Authenticator, pending-triage
