### ISSUE TITLE
[Feedback]withauthenticator Error

### ISSUE THREAD

**Issue by CalebGDM** [aws-amplify/amplify-ui#574] opened 2021-10-23 18:46 UTC
**Page**: [`/start/getting-started/installation/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/installation/q/integration/react-native)

**Feedback**:

I'm trying to implement authentication withwithAuthenticator but when I try to sing up it shows me that error... There will be a way to fix the issue?

Some screenshots of the error
![Simulator Screen Shot - iPhone 13 - 2021-10-23 at 13 36 44](https://user-images.githubusercontent.com/50932315/138567836-cb72d043-dd67-4b22-836b-47a2b199f0a4.png)

![Simulator Screen Shot - iPhone 13 - 2021-10-23 at 13 36 51](https://user-images.githubusercontent.com/50932315/138567838-b1fc7ba5-39f3-4f20-a439-a580ad38e837.png)

<img width="541" alt="Captura de Pantalla 2021-10-23 a la(s) 13 43 59" src="https://user-images.githubusercontent.com/50932315/138567927-88ee8c20-1d4f-4ab7-86a3-cb479c796c3e.png">

**Comment by wlee221** [comment] 2021-11-29 07:02
Hello @CalebGDM, is this with `aws-amplify-react-native` package? If so, I believe this is duplicate of https://github.com/aws-amplify/amplify-js/issues/6845 and has been resolved in `aws-amplify-react-native@6.0.1`.

**Closed** 2022-01-06 23:40 UTC
Labels: bug, React Native, Authenticator, pending-response, pending-triage
