### ISSUE TITLE
FR (Authenticator): Ability to translate custom placeholders/labels

### ISSUE THREAD

**Issue by einargudnig** [aws-amplify/amplify-ui#1807] opened 2022-05-02 14:18 UTC
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Webpack 5

### Please describe your bug.

I'm translating the `<Autenticator />` component. 

It will have English, Icelandic, and Danish language.
I made a separate language file that holds the translations, and use `I18n.setLanguage()` to use said file.

I want to add custom placeholder and labels to the `<Authenticator />` 
see here: https://ui.docs.amplify.aws/components/authenticator#customization

The `formFields` object has the custom placeholders and passes them as props to the `Authenticator`.
When I change the language, (you can press the "en", "is", or "da" buttons at the top to change the language) the default strings in the `Authenticator` do change their translations but the custom placeholders and labels do **not** translate.

### What's the expected behaviour?

That the placeholder and labels will also be translated when the language is changed!

![Screenshot 2022-05-02 at 14 07 31](https://user-images.githubusercontent.com/17381009/166248049-f2876761-c70d-4bc8-98d7-1ad209c013ba.png)

The strings with the red underline should also be translated to Icelandic like the other strings on the `Authenticator` are

### Help us reproduce the bug!

Here is a sandbox that behaves in the same way.

https://codesandbox.io/s/musing-thunder-4fgflq?file=/src/App.js:535-536

Note that the Authenticator **does** translate the default strings, so strings like "Password" are translated when there is **not** a custom placeholder added to the password field. But by adding it it does not translate the same string .

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by ErikCH** [comment] 2022-05-02 17:03
Hi @einargudnig !

Thanks for the codesandbox! That's very helpful.

I was able to reproduce this, and you're right. We don't have any way to dynamically update translations when they get updated. Thats on our list of features we want to add. This might be a duplicate of this [issue](https://github.com/aws-amplify/amplify-ui/issues/256)

**Comment by OlgaMaslova** [comment] 2022-08-09 08:13
Hello, any update on that issue? Facing the same problem! Thanks.

**Comment by reesscot** [comment] 2023-06-01 00:24
Closing this one as a duplicate of https://github.com/aws-amplify/amplify-ui/issues/256

**Closed by reesscot** 2023-06-01 00:24 UTC
Labels: feature-request, Authenticator
