### ISSUE TITLE
How does one configure <Authenticator> component  to support SSO (SAML providers) configured for Cognito user Pool?

### ISSUE THREAD

**Issue by quarryman** [aws-amplify/amplify-ui#4460] opened 2023-09-19 18:00 UTC
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

CRA

### What browsers are you seeing the problem on?

Chrome

### Please describe your bug.

Its is not clear if its possible to configure Authenticator component to work with SSO (custom SAML provider, not Google/Facebook OAuth).
SAML provider is configured for Cognito user pool and it doesnt make any effect on Authenticator generated login screen.

I have 2 questions here 
- is it possible to configure Authenticator for SSO support to lets say render 'Login with SSO' button or one must manually add SSO button with Auth.FederatedSignIn() api invocation?
- if possible, can Authenticator component handle SSO logic or user must be redirected to hosted UI and this is a must?

Thanx

### What's the expected behaviour?

Once certain configuration provided Authenticator component is expected to render login with SSO option along with other available login options

### Help us reproduce the bug!

Configure SAML provider for connected  user pool and see no changes in signIn screen

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by lavr001** [comment] 2023-09-21 18:47
Possible duplicate of this existing [issue#2020](https://github.com/aws-amplify/amplify-ui/issues/2020)

**Closed** 2023-09-26 18:01 UTC
Labels: duplicate
