### ISSUE TITLE
Can't resolve './@aws-amplify/ui/styles.css'

### ISSUE THREAD

**Issue by nextdooroldwang** [aws-amplify/amplify-ui#1005] opened 2021-12-16 09:10 UTC
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### Please describe your bug.

```
 error  in ./node_modules/@aws-amplify/ui-react/dist/index.css

Module build failed (from ./node_modules/@umijs/bundler-webpack/lib/webpack/plugins/mini-css-extract-plugin/src/loader.js):
ModuleNotFoundError: Module not found: Error: Can't resolve './@aws-amplify/ui/styles.css' in '/node_modules/@aws-amplify/ui-react/dist'
```

### What's the expected behaviour?

Compiled successfully

### Help us reproduce the bug!

1.yarn add aws-amplify @aws-amplify/ui-react
2.import '@aws-amplify/ui-react/styles.css';
3.yarn start

**I opend the CSS Modules in my program。**

### Code Snippet

```typescript
import { Amplify } from 'aws-amplify';
import { Authenticator } from '@aws-amplify/ui-react';

import '@aws-amplify/ui-react/styles.css';
import awsExports from './aws-exports';
import styles from './index.less';

Amplify.configure(awsExports);

export default function Layout() {
    return (
      <Authenticator>
        {({ signOut, user }) => (
          <main>
            <h1>Hello {user.username}</h1>
            <div onClick={signOut}>Sign out</div>
          </main>
        )}
      </Authenticator>
    );
}

```

### Additional information and screenshots

    "@aws-amplify/ui-react": "^2.1.5",
    "aws-amplify": "^4.3.11",

Mini Showcase Repository(REQUIRED)
https://github.com/nextdooroldwang/umi-sample.git

**Comment by ericclemmons** [comment] 2021-12-16 19:45
So it looks like `@aws-amplify/ui-react/styles.css` is correctly resolving, but the `@import"@aws-amplify/ui/styles.css"` isn't:

> https://unpkg.com/browse/@aws-amplify/ui-react@2.1.5/dist/index.css

It looks like the ESM `exports` aren't being followed for https://unpkg.com/browse/@aws-amplify/ui@3.0.5/package.json 

For comparison, the first level works:
> https://unpkg.com/browse/@aws-amplify/ui-react@2.1.5/package.json

**Comment by nextdooroldwang** [comment] 2021-12-17 04:22
How should I import css correctly

**Comment by moltar** [comment] 2021-12-18 09:54
This works in TSX:

```ts
import '@aws-amplify/ui-react/styles.css'
```

This works in SCSS:

```scss
@import "@aws-amplify/ui-react/styles.css";
```

**Comment by reesscot** [comment] 2021-12-21 00:09
Hi @nextdooroldwang, thank for reporting this issue. I was able to reproduce this error, and it's now fixed on the main branch. It will be generally available when the next release goes out. In the meantime you can test out the fix by installing the change with the following pre-release tag:

```
npm i @aws-amplify/ui-react@0.0.0-next-59d8b8e-20211120234739
```

**Closed by reesscot** 2021-12-21 00:09 UTC
