### ISSUE TITLE
AmplifySignUp doesn't detect values of text fields after initial submission failure

### ISSUE THREAD

**Issue by jagonzalr** [aws-amplify/amplify-ui#298] opened 2021-08-12 10:31 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Not applicable

### Amplify Categories

Not applicable

### Environment information

<details>

```
# Put output below this line

System:
    OS: macOS 11.5.1
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Memory: 944.93 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.5 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.14 - /usr/local/bin/npm
  npmPackages:
    @aws-amplify/ui-react: ^1.2.8 => 1.2.8 
    @popperjs/core: ^2.9.2 => 2.9.3 
    @testing-library/jest-dom: ^5.11.4 => 5.14.1 
    @testing-library/react: ^11.1.0 => 11.2.7 
    @testing-library/user-event: ^12.1.10 => 12.8.3 
    autoprefixer: ^9.8.6 => 9.8.6 
    aws-amplify: ^4.2.2 => 4.2.2 
    bootstrap: ^5.0.2 => 5.1.0 
    bootstrap-icons: ^1.5.0 => 1.5.0 
    husky: ^7.0.0 => 7.0.1 
    lerna: ^4.0.0 => 4.0.0 
    node-sass: ^6.0.1 => 6.0.1 
    prettier: ^2.3.2 => 2.3.2 
    pretty-quick: ^3.1.1 => 3.1.1 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    react-scripts: 4.0.3 => 4.0.3 
    redux-logger: ^3.0.6 => 3.0.6 
    workbox-background-sync: ^5.1.3 => 5.1.4 
    workbox-broadcast-update: ^5.1.3 => 5.1.4 
    workbox-cacheable-response: ^5.1.3 => 5.1.4 
    workbox-core: ^5.1.3 => 5.1.4 
    workbox-expiration: ^5.1.3 => 5.1.4 
    workbox-google-analytics: ^5.1.3 => 5.1.4 
    workbox-navigation-preload: ^5.1.3 => 5.1.4 
    workbox-precaching: ^5.1.3 => 5.1.4 
    workbox-range-requests: ^5.1.3 => 5.1.4 
    workbox-routing: ^5.1.3 => 5.1.4 
    workbox-strategies: ^5.1.3 => 5.1.4 
    workbox-streams: ^5.1.3 => 5.1.4 

```

</details>

### Describe the bug

When using a custom `AmplifyAuthenticator` and trying to sign up, if registration fails because only one of the fields was wrong, the user updates the field in the form to fix it. Because the user is only updating one field it always throws `Password cannot be empty` or `Email cannot be empty`. The only way to overcome that is to modify both email and password fields before submitting. If the user only modifies one field the form always fails.

### Expected behavior

When a user fixes the form and clicks submit again the form should call the Cognito API to create the user.

### Reproduction steps

1. Go to Sign Up page
2. Fill out sign up form with incorrect data (email already been used or incorrect password policy)
3. Submit and wait for failure
4. Fix only one of the text inputs (email or password)
5. Submit
6. If email was updated it says password is empty (it is not). If password is updated it says email is empty (it is not)
7. Update both fields and submit
8. Submission now works

### Code Snippet

Wrapping `App.jsx` with custom `withAuthenticator`

Code for `withAuthenticator.jsx`

```javascript
import { useEffect, useState } from 'react'
import { Auth, appendToCognitoUserAgent } from '@aws-amplify/auth'
import { Hub, Logger } from '@aws-amplify/core'
import {
  AmplifyContainer,
  AmplifyAuthenticator,
  AmplifyAuthContainer,
  AmplifySignIn,
  AmplifySignUp,
  AmplifyConfirmSignIn,
  AmplifyConfirmSignUp,
  AmplifyForgotPassword,
  AmplifyRequireNewPassword,
  AmplifyTotpSetup,
  AmplifyVerifyContact
} from '@aws-amplify/ui-react'
import {
  UI_AUTH_CHANNEL,
  TOAST_AUTH_ERROR_EVENT,
  AuthState,
  onAuthUIStateChange
} from '@aws-amplify/ui-components'

import Toast from '../Toast'

const logger = new Logger('withAuthenticator')

function applyStylesToShashowComponent(querySelector) {
  const style = document.createElement('style')
  style.innerHTML = '.button { border-radius: 0.25rem!important; }'
  const host = document.querySelector(querySelector)
  host.shadowRoot.appendChild(style)
}

function withAuthenticator(Component, authenticatorProps) {
  const AppWithAuthenticator = props => {
    const [errorMessage, setErrorMessage] = useState(null)
    const [signedIn, setSignedIn] = useState(false)

    useEffect(() => {
      Hub.listen(UI_AUTH_CHANNEL, handleHubEvents)
      return () => {
        Hub.remove(UI_AUTH_CHANNEL, handleHubEvents)
      }
    })

    useEffect(() => {
      appendToCognitoUserAgent('withAuthenticator')
      const shadowComponents = [
        'amplify-sign-in',
        'amplify-sign-up',
        'amplify-confirm-sign-in',
        'amplify-confirm-sign-up',
        'amplify-forgot-password',
        'amplify-require-new-password',
        'amplify-totp-setup',
        'amplify-verify-contact'
      ]

      shadowComponents.forEach(applyStylesToShashowComponent)
      return checkUser()
    }, [])

    function checkUser() {
      setUser()

      return onAuthUIStateChange(authState => {
        if (authState === AuthState.SignedIn) {
          setSignedIn(true)
        } else if (authState === AuthState.SignedOut) {
          setSignedIn(false)
        }
      })
    }

    function handleHubEvents({ payload }) {
      setErrorMessage(null)
      logger.debug(payload)

      if (payload.event === TOAST_AUTH_ERROR_EVENT && payload.message) {
        setErrorMessage(payload.message)
      }
    }

    function onClickCloseError(e) {
      e.preventDefault()
      setErrorMessage(null)
    }

    async function setUser() {
      try {
        const user = await Auth.currentAuthenticatedUser()
        if (user) setSignedIn(true)
      } catch (err) {
        logger.debug(err)
      }
    }

    if (!signedIn) {
      return (
        <AmplifyContainer>
          <AmplifyAuthContainer>
            {errorMessage && (
              <Toast message={errorMessage} onClickClose={onClickCloseError} />
            )}
            <AmplifyAuthenticator
              {...authenticatorProps}
              {...props}
              usernameAlias={'email'}
              hideToast={true}
            >
              <AmplifySignIn slot={'sign-in'} usernameAlias={'email'} />
              <AmplifySignUp
                slot={'sign-up'}
                usernameAlias={'email'}
                formFields={[
                  {
                    type: 'email',
                    placeholder: 'Enter your email address'
                  },
                  {
                    type: 'password',
                    placeholder: 'Enter your new password',
                    hint: 'Must be 8 characters long, at least 1 capital letter, 1 lower case letter, 1 number and 1 symbol.'
                  }
                ]}
              />
              <AmplifyConfirmSignIn slot={'confirm-sign-in'} />
              <AmplifyConfirmSignUp
                slot={'confirm-sign-up'}
                usernameAlias={'email'}
              />
              <AmplifyForgotPassword
                slot={'forgot-password'}
                usernameAlias={'email'}
              />
              <AmplifyRequireNewPassword slot={'require-new-password'} />
              <AmplifyTotpSetup slot={'totp-setup'} />
              <AmplifyVerifyContact slot={'verify-contact'} />
            </AmplifyAuthenticator>
          </AmplifyAuthContainer>
        </AmplifyContainer>
      )
    }

    return <Component {...props} />
  }

  return AppWithAuthenticator
}

export default withAuthenticator
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Manual configuration

```javascript
Amplify.configure({
  Auth: {
    identityPoolId: 'us-east-1:#######',
    region: 'us-east-1',
    userPoolId: 'us-east-1_#######',
    userPoolWebClientId: '#######',
    mandatorySignIn: false,
    authenticationFlowType: 'USER_SRP_AUTH'
  }
})
```

### Additional information and screenshots

https://user-images.githubusercontent.com/3858265/129182560-00111fe5-d5bd-4ad0-958a-eb4bcc535c79.mov

**Comment by ericclemmons** [comment] 2021-11-05 16:39
Confirmed this is fixed in `@next`:

https://user-images.githubusercontent.com/15182/140546236-f17facf0-4b5b-446a-91f6-4e84f1de2e11.mp4

This also works as expected for custom fields appended to the form:
> https://ui.docs.amplify.aws/ui/components/authenticator?platform=react#sign-up-fields


Unfortunately, the architecture for the previous implementation around `formFields` basically wipes out values between renders, which is what caused this bug.

The new implementation respects existing values and correctly updates them.

**Closed by ericclemmons** 2021-11-05 16:39 UTC
Labels: bug, Auth, React

**Comment by therobwatson** [comment] 2021-11-11 15:36
@ericclemmons Regarding the linked documentation, can I pass a `formFields`(?) prop of some sort to `<Authenticator.SignUp.FormFields />` to omit the `phone_number` field?

**Comment by therobwatson** [comment] 2021-11-15 13:37
Sorry @ericclemmons , I do not know where else to ask this question.  I am trying to use the `@next` version because of an issue with mobile devices and the sign up.  The fields are not recognized by the validator (similar to this issue here).

I was able to omit the `phone_number` field with the `@next` version using some very brittle code below and I am hoping there is a better solution coming down the pike for the `@next` version.

Again, this code is brittle and I want to avoid using it.  However, I think my hands are tied at the moment until I have a documented solution for omitting the `phone_number` field.

`export default withAuthenticator(Wallets, {
  usernameAlias: "email",
  components: {
    SignUp: {
      FormFields() {

        console.log(Authenticator.SignUp.FormFields());
        let passwordFormField
        let passwordConfirmFormField;
        let emailFormField;
        Object.entries(Authenticator.SignUp.FormFields()).forEach( ([key, value]) => {
          if (key === "props") {
            if (value.hasOwnProperty("children")) {
              value.children.forEach( (formField, index) => {
                //console.log(index, formField);
                console.log(typeof formField, index);
                switch (index) {
                  case 0: // alias "username"
                    return; // continue to next
                  case 1: // name "password"
                    passwordFormField = formField;
                    return;
                  case 2: // name "confirm_password"
                    passwordConfirmFormField = formField;
                    return;
                  case 3: // formField === false
                    return;
                  case 4: // formField is an array of additional fields
                      formField.forEach ( (additionalFormField, additionalFormFieldIndex ) => {
                        switch (additionalFormFieldIndex) {
                          case 0: // key "email"
                            emailFormField = additionalFormField;
                            return;
                          case 1: // key "phone_number"
                            return;
                          default:
                            console.warn("Unexpected additional form field", additionalFormField);
                            return;
                        }
                      });
                      return;
                  default:
                    console.warn("Unexpected form field", formField);
                    return;
                }
              });
            }
          }
        });

        return (
          <>
            {emailFormField}
            {passwordFormField}
            {passwordConfirmFormField}
          </>
        )
      }
    }
  }
});`
![next-release-actually-recognizes-input-fields](https://user-images.githubusercontent.com/1254541/141790982-f352ed9e-e5b2-4b6b-8546-838f4f04cfc6.png)

**Comment by ericclemmons** [comment] 2021-11-16 21:18
@therobwatson There have been some recent adjustments with zero-configuration that should help in this case.  I'm assuming that `phone_number` shouldn't be shown, but it was because we originally had it hard-coded.

But now, `amplify pull` gives me an `aws-exports.js` **without** `phone_number` listed.

Can you share your `aws-exports.js` after installing `@aws-amplify/cli@latest` and running `amplify pull`?

```js
/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:••••",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_••••",
    "aws_user_pools_web_client_id": "••••",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_cognito_login_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;

```

This results in the following UI:
> ![Screen Shot 2021-11-16 at 3 16 53 PM](https://user-images.githubusercontent.com/15182/142067107-51929a6b-ed49-4ad9-88c3-8f34d40abd13.png)
 
In fact, even the https://github.com/aws-amplify/amplify-ui/tree/main/environments/auth-with-username UI doesn't include `phone_number`:
> ![Screen Shot 2021-11-16 at 3 17 31 PM](https://user-images.githubusercontent.com/15182/142067233-abb3ff2d-22c9-4d36-bf8d-5de50c9ce859.png)

**Comment by therobwatson** [comment] 2021-11-18 13:27
Thanks @ericclemmons !  I upgraded `@aws-amplify/cli` from version `6.4.0`¹ to `latest` (`7.3.6`) and `phone_number` is now omitted without any need for customizing the rendered fields.

I did a quick acid test by creating a new account and it worked perfectly for me.

I don't think I need any further assistance with this issue.  Thanks again!

--
¹ `6.4.0` may seem outdated but is only a week old, as far as I can tell. I'm not sure if this matters, but `6.4.0` was installed last week via the method provided in Amplify Admin UI: `curl -sL https://aws-amplify.github.io/amplify-cli/install | bash && $SHELL`

**Comment by therobwatson** [comment] 2021-11-22 14:13
Sorry @ericclemmons , I can't seem to omit the `email` input from `SignUp` using `usernameAlias`:

I can't seem to find the right syntax nor documentation for this.  It was working for me during my initial tests and now I've lost it somehow.  Please help.

None of these attempts work now, it seems:

```javascript
export default withAuthenticator(Component, {
  usernameAlias: "email",
  components: {
    SignUp: {
      UsernameAlias: "email",
      usernameAlias: "email",
      UsernameAlias: "Email",
      usernameAlias: "Email",
      FormFields() {
        return (
          <Authenticator.SignUp.FormFields usernameAlias={"email"} UsernameAlias={"email"} usernameAlias={"Email"} UsernameAlias={"Email"} />
        )
      }
    }
  }
});
```

**Comment by ericclemmons** [comment] 2021-11-22 16:06
Try setting your `loginMechanisms: ['email']`:
> <img width="903" alt="Screen Shot 2021-11-22 at 10 03 44 AM" src="https://user-images.githubusercontent.com/15182/142894867-cb12da72-588c-43bc-9eeb-40ad8228c4bb.png">
> – https://ui.docs.amplify.aws/components/authenticator#loginmechanisms

Can you screenshot what your SignUp screen looks like so I can understand what you want it to look like?

`Email` will be required if it's a verification mechanism or one of the required `signUpAttributes`:
> https://ui.docs.amplify.aws/components/authenticator#signupattributes

**Comment by therobwatson** [comment] 2021-11-22 22:08
Thanks @ericclemmons !  Yes, your suggestion worked.  Sorry, I'm getting used to the new syntax and it seems like my mishmash combo seemed to work in some nightly(?) `@next` build.

The following worked for me (using a fresh `@next` install, if it matters):
```javascript
export default withAuthenticator(Component, {
  loginMechanisms:['email'],
  components: {
    SignUp: {
      FormFields() {
        return (
          <Authenticator.SignUp.FormFields />
        )
      }
    }
  }
});
```
