### ISSUE TITLE
Support - Choose preferred delivery method SMS or TOTP MFA

### ISSUE THREAD

**Issue by HanojHanu** [aws-amplify/amplify-ui#4427] opened 2023-09-10 05:18 UTC
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

MFA TOTP 

( Cognito user - any )
![image](https://github.com/aws-amplify/amplify-ui/assets/53425981/826435c4-8fe5-4c67-a80d-97c2b4c360e6)

Amplify  UI - 
![image](https://github.com/aws-amplify/amplify-ui/assets/53425981/5551d521-83d2-4bee-bfce-f5c291816cce)

### Please describe a solution you'd like.

it should have display option to pick one "MFA" or "TOTP"
https://docs.amplify.aws/lib/auth/mfa/q/platform/js/#advanced-use-cases

# with the help of hosted ui from cognito
![image](https://github.com/aws-amplify/amplify-ui/assets/53425981/36634a4b-3af1-431c-9e44-093f31b5f9f7)

### We love contributors! Is this something you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by HanojHanu** [comment] 2023-09-10 05:20
# Error log - Amplify

![image](https://github.com/aws-amplify/amplify-ui/assets/53425981/97f566a4-f284-4980-9352-99567e56c7eb)

**Comment by calebpollman** [comment] 2023-09-26 18:04
Marking as a duplicate of https://github.com/aws-amplify/amplify-ui/issues/3767 and closing

**Closed by calebpollman** 2023-09-26 18:04 UTC
Labels: feature-request, Authenticator
