### ISSUE TITLE
useDataStoreBinding's isLoading props value is getting false even though data is being fetched

### ISSUE THREAD

**Issue by jaythakor-ai** [aws-amplify/amplify-ui#1729] opened 2022-04-20 10:47 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-adminui/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-adminui/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Region

us-east-2

### Amplify CLI Version

7.6.26

### If applicable, what version of Node.js are you using?

14.16.0

### What operating system are you using?

Windows

### Browser type?

Chrome

### Describe the bug

Even though my data from the datastore is being fetched, the isLoading props of the useDataStoreBinding function are getting false.

### Expected behavior

The prop value of isLoading should be true till the data is not fully fetched.

### Reproduction steps

1. create the collection in the Amplify Studio.
2. Bind any database value into the collection.
3. Use this collection in the UI and see the result.

### Additional information

Below is the code snippet that can help you to repro the issue.

import { useDataStoreBinding } from "@aws-amplify/ui-react/internal";

const items = useDataStoreBinding({
    type: "collection",
    model: 'Your Model Name',
  });

console.log('items loading prop value', items.isLoading);

**Comment by reesscot** [comment] 2022-04-20 17:13
Hi @jaythakor-ai,
Thank you for reporting this issue, we will looking into this. However, this hook is not ready for direct public consumption (hence why it is marked as `internal`) and is only used inside of Amplify Studio generated components. We are working on a better overall public API for DataStore loading and collections.

**Comment by reesscot** [comment] 2022-04-20 17:25
I am unable to reproduce an issue with this hook. While it initially will return false, as soon as the fetch call starts I am seeing `isLoading` returning `true`. Closing as this is an internal hook, and was unable to reproduce any issue with Studio.

@jaythakor-ai If you still feel this is an issue with an unedited component generated by Studio, please provide the studio generated code that is causing the issue and reopen this ticket.

**Closed by reesscot** 2022-04-20 17:25 UTC
Labels: Studio
