### ISSUE TITLE
FR: Authenticator - Optional MFA

### ISSUE THREAD

**Issue by ErikCH** [aws-amplify/amplify-ui#2249] opened 2022-07-05 18:29 UTC
@jeff-wishnie

Vue3 UI Framework
ui-vue/Authenticator component
AmplifyJS 'Auth'
Cognito User Pool

What is the approach to allowing users to choose a MFA mode (none, TOTP, SMS) at account creation time?

I think the approach would be somthing like the following, but I am not clear on where to hook into the process:

    Add fields to the sign-up-fields slot to enable MFA--e.g. a 'MFA Options' pulldown with 'None', 'SMS', and 'Auth App' options
    After user clicks 'Create account', capture user's choice
    After user is created, call Auth.setPreferredMFA() based on user's choice

Am I on the right track?
Is there an easier way e.g. (set some options on the sign-up component)?
If this is the right track, where can I hook into the process (catch an event emitted by the sign-up component?) to read the user's choice and call setPreferredMFA?

Thanks!!

----
@jeff-wishnie
If the UserPool is configured to require a single method (I've tested with TOTP) then the machine does bring the user to the QR code for scanning the seed into an auth app.

But the specific use case I need to support is user-chooses None, SMS, or TOTP

In addition, we aren't requiring phone number when creating an account, so if the user selects SMS, we would at that time collect a phone number.

So full flow would be:

Create account
- No MFA chosen -> user added to User Pool -> auto-verify attributes verified (email in our case)
- TOTP chosen -> user added to User Pool -> auto-verify attributes -> TOTP seed establish & verified
- SMS chosen -> user added to User Pool -> phone # collected -> auto-verify attrs (email & phone) -> SMS code sent & verified

---------
_Originally posted by @TuTomasz
Have there been any developments or resolutions to this issue? If UserPool is configured as "optional" for MFA. The setupToTP component in amplify UI never triggers on sign-up or first login. I am able to `setPreferredMFA` from within the app and configure the user MFA settings and have the challenge appear on subsequent logins. How to trigger the setupTOTP screen on sign-up is the question that I can't seem to find an answer to. I would appreciate some guidance Thank You.

---------
@RFM69CW

We also want that optional MFA feature. We implemented a workaround with overriding the handleSign and handle different challenges:

Example for Angular:
``` html
<amplify-authenticator [services]="services"></amplify-authenticator >
```

``` typescript
export class AuthenticationComponent {
  public services = {
    async handleSignIn({
      username,
      password,
    }: {
      username: string;
      password: string;
    }): Promise<any> {
      return Auth.signIn(username, password).then(res => {
        // do this only for specific users. Check E-Mail/Role/Flag or sth. You can also let the user decide by an checkbox in UI
        if (res.challengeName !== 'SOFTWARE_TOKEN_MFA') {
          res.challengeName = 'MFA_SETUP';
        }
        return res;
      });
    }
  };
}
```
After successfully setup MFA please make sure to enable the preferred mfa for the user. 
``` typescript
Auth.setPreferredMFA(user, 'SOFTWARE_TOKEN_MFA');
```
Here it gets a bit ugly. To set the setPreferredMFA listen to the AuthenticatorService and setPreferredMFA when user is authenticated and totpSecretCode is present. That only happens after successfully setup totp:

``` typescript
export class AuthenticationComponent {
  // code above ...
constructor(
    public readonly authenticator: AuthenticatorService) {
      this.authenticator.subscribe(event => {
        if (event.authStatus === 'authenticated' && event.totpSecretCode) {
          console.log('set user mfa')
          Auth.currentAuthenticatedUser().then(user => Auth.setPreferredMFA(user, 'SOFTWARE_TOKEN_MFA'));
        }
      });
    }
}
```

Hope that will help you :-)

**Comment by calebpollman** [comment] 2023-09-26 18:13
Closing as duplicate of https://github.com/aws-amplify/amplify-ui/issues/3767

**Closed by calebpollman** 2023-09-26 18:13 UTC
Labels: feature-request, Authenticator
