### ISSUE TITLE
SelectField not respecting size="small"

### ISSUE THREAD

**Issue by austin-garner** [aws-amplify/amplify-ui#2465] opened 2022-08-14 05:59 UTC
Setting size small on SelectField is not alerting the size of the select field. It is not applying the `amplify-field--small` class to the element like it does in the example.

"@aws-amplify/ui-react": "^3.3.0"

```
<SelectField
  label="Fruit"
  size="small"
  descriptiveText="What's your favorite fruit?"
>
  <option value="apple">Apple</option>
  <option value="banana">Banana</option>
  <option value="orange">Orange</option>
</SelectField>
```

**Comment by slaymance** [comment] 2022-08-15 22:05
Hey @austin-garner, I was unable to reproduce this issue using your code sample and the `@aws-amplify/ui-react@3.4.0` package. Are you doing any of your own [custom theming through Amplify](https://ui.docs.amplify.aws/react/theming)?

**Comment by Milan-Shah** [comment] 2022-09-30 14:26
@austin-garner We have been unable to reproduce your issue, doesnt mean the issue may not exist. We are closing the issue, but feel free to reopen if you are still having a problem applying theme.

**Closed by Milan-Shah** 2022-09-30 14:26 UTC
Labels: pending-response
