### ISSUE TITLE
Next.js - component state is being lost when router.push is called from within an Authenticator component

### ISSUE THREAD

**Issue by chris-bloomfield** [aws-amplify/amplify-ui#1491] opened 2022-03-08 17:13 UTC
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Next.js

### Please describe your bug.

When using the Authenticator component inside a Next.js app I'm trying to use Next's `useRouter` hook to add a query string to the current URL, however when I do this, the current state of any components inside the `Authenticator` is being lost.

### What's the expected behaviour?

Would expect component state to persist as long as the URL still points to the same page component (i.e. `pages/examplePage` to `pages/examplePage?query=string`).

### Help us reproduce the bug!

 - Create a Next.js app
 - Amend `_app.js` with the code snippet in the section below.
 - This should display two buttons that update their state when clicked:
 
![image](https://user-images.githubusercontent.com/13033041/157289044-eaecc7eb-bbe7-4cb1-8ab1-0f136568d4bf.png)
 - After clicking the 'Add query string to URL' button the state of the component inside the Authenticator is reset to 0, but the one outside the Authenticator persists.
 
![image](https://user-images.githubusercontent.com/13033041/157289283-168444cd-e2b7-4c0a-a7ba-c2a15f4d92b8.png)

 

### Code Snippet

```typescript
import { Amplify } from "aws-amplify";
import { Authenticator } from "@aws-amplify/ui-react";
import '@aws-amplify/ui-react/styles.css';
import awsExports from './aws-exports';
import { useRouter } from "next/router";
import { useState } from "react";

Amplify.configure(awsExports);

const ComponentWithState = () => {
  const [test, setTest] = useState(0);
  return (
    <>
      {/* Increment variable state */}
      <button onClick={() => setTest((t) => t + 1)}>{test}</button>
    </>
  );
};

function MyApp({ Component, pageProps }) {
  const router = useRouter();
  return (
    <>
      <button
        onClick={() =>
          router.push({ query: { hello: "world" } }, undefined, {
            shallow: true,
          })
        }
      >
        Add query string to URL
      </button>
      <br />
      Outside Authenticator: <ComponentWithState />
      <br />
      <Authenticator>
        {({ signOut, user }) => (
          <>
            Inside Authenticator: <ComponentWithState />
          </>
        )}
      </Authenticator>
    </>
  );
}

export default MyApp;
```

**Comment by ErikCH** [comment] 2022-03-09 16:50
Hi @chris-bloomfield !

Thanks for bringing this up. We do have a few issues with our `useAuthenticator` hooks working with refreshes and certain changes. It's similar to this [issue](https://github.com/aws-amplify/amplify-ui/issues/1332). We'll be looking at this soon

**Comment by jacoblogan** [comment] 2022-04-25 16:43
Hi @chris-bloomfield,
Thanks for opening this issue. There have been a lot of improvements to the Authenticator and with the latest version of @aws-amplify/ui-react and following your steps to reproduce this issue I am not able to reproduce it.  Can you confirm for me that the issue is either resolved or still exists under the latest version of the package?

**Comment by jacoblogan** [comment] 2022-05-03 20:39
Cannot reproduce with the latest release, closing this issue.  Please reopen the issue if you are still experiencing this under the latest release.

**Closed by jacoblogan** 2022-05-03 20:39 UTC
Labels: bug, Authenticator, pending-response
