### ISSUE TITLE
Better customization options for form fields

### ISSUE THREAD

**Issue by troncoso** [aws-amplify/amplify-ui#2152] opened 2022-06-20 21:08 UTC
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

I know that the `<Authenticator>` component supports customizing the `<SignUp>` and `<ForceNewPassword>` form fields like so:

```typescript
const components: DefaultComponents = {
    SignUp: {
        FormFields() {
            return (
                <>
                    <FormTextField label="Email" name="email" />
                    <FormTextField label="Password" name="password" type="password" />
                    <FormTextField label="Confirm Password" name="confirm_password" type="password" />
                </>
            );
        },
    },
};
```

However, there are 2 problems:

1. This doesn't seem to be available for any other form components such as `<SignIn>`.
2. It would be very tedious to have to override each form just to modify the input

It would be really nice to be able to set a custom component for the form inputs overall. I know we can customize the CSS, but this can only take things so far. For example, that `<FormTextField>` in my example manages the label using the input placeholder and a `<fieldset>` element. I'd be very hard-pressed to replicate what it does with only custom styling.

### Please describe a solution you'd like.

The one solution I can think of is to create a "FormFieldBuilder" sort of function. It would accept any attributes to pass to the `<input>` such as `name` and `type` and it'd be up to the user to use those in their own input component where it makes sense:

```javascript
const components = {
    FormField({ label, ...inputProps }) {
        // const { name, autoComplete, type, aria-describedby, etc } = inputProps;
        return (
            <div>
                <label>{label}</label>
                <input {...inputProps} />
            </div>
        );
    }
};
```

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by calebpollman** [comment] 2023-09-26 18:10
Closing as duplicate of https://github.com/aws-amplify/amplify-ui/issues/2124

**Closed by calebpollman** 2023-09-26 18:10 UTC
Labels: feature-request, Authenticator, React
