### ISSUE TITLE
ESM build cannot be loaded by Node.js

### ISSUE THREAD

**Issue by brillout** [aws-amplify/amplify-ui#3155] opened 2022-12-10 14:07 UTC
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Vite + vite-plugin-ssr

### What browsers are you seeing the problem on?

Chrome

### Please describe your bug.

Node.js cannot import `@aws-amplify/ui-react`:

```
(node:30335) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
node_modules/@aws-amplify/ui-react/dist/esm/index.js:1
```

The fix is to set `"type": "module"` in `node_modules/@aws-amplify/ui-react/package.json`, but then another error is thrown:

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'node_modules/lodash/debounce' imported from node_modules/@aws-amplify/ui-react/dist/esm/primitives/Collection/Collection.js
Did you mean to import lodash@4.17.21/node_modules/lodash/debounce.js?
    at new NodeError (node:internal/errors:372:5)
  code: 'ERR_MODULE_NOT_FOUND'
}
```

The problem here is that `node_modules/@aws-amplify/ui-react/dist/esm/primitives/Collection/Collection.js` contains `import a from"lodash/debounce"` but it should be `import a from"lodash/debounce.js"` instead. (If you change that line, you'll see the error go away but another similar error is thrown then.)

### What's the expected behaviour?

No errors.

### Help us reproduce the bug!

Minimal reproduction: https://github.com/brillout/aws-amplify-bug-esm-build.

(In case you're curious, this is the real-world reproduction: https://github.com/micah-redwood/vite-prerender-aws-amplify-compat. With the Vite workaround I mention down below: https://github.com/brillout/vite-prerender-aws-amplify-compat.)

### Additional information and screenshots

I'm the author of [vite-plugin-ssr](https://vite-plugin-ssr.com/); one of my users reported this bug.

For Vite, a workaround is to add `@aws-amplify/ui-react` to [`vite.config.js.noExternal`](https://vitejs.dev/config/ssr-options.html#ssr-noexternal).

But other stacks don't have this possibility, e.g. companies that implement SSR themselves without using a bundler such as Vite or webpack. See the minimal reproduction.

Possibly related: https://github.com/aws-amplify/amplify-ui/issues/756. (Since SvelteKit uses Vite.)

**Comment by reesscot** [comment] 2022-12-12 17:24
@brillout Can you confirm which versions of Node you're seeing this in? From your example, it looks like you've primarily tested Node 18, is that correct?

**Comment by brillout** [comment] 2022-12-12 17:25
That is correct

**Comment by 0618** [comment] 2022-12-12 17:51
Thank you. I was able to reproduce it with NodeJS 16

**Comment by ljharb** [comment] 2023-01-03 19:25
type module isn't required; better and simpler would be to make ESM files have an `.mjs` extension.

**Comment by reesscot** [comment] 2023-01-11 16:33
Just an update that we are making progress on this and will have a PR out soon.

**Comment by reesscot** [comment] 2023-01-13 18:33
@brillout @micah-redwood @johanhenrikssn @sheremet-va @ljharb We've published the fix for this to a `node-esm` tag, if anyone is willing to test it out:
```
npm install @aws-amplify/ui-react@node-esm
```

I've tested it out with https://github.com/brillout/aws-amplify-bug-esm-build and it appears to be working.

**Closed** 2023-01-27 19:11 UTC
Labels: bug, Authenticator, build

**Comment by reesscot** [comment] 2023-02-01 17:43
The ESM fix has been released in `@aws-amplify/ui-react@4.3.6`

```
npm install @aws-amplify/ui-react@latest
```

@brillout @ljharb @micah-redwood, @johanhenrikssn, @sheremet-va, please let us know if it's working for you.

**Comment by micah-redwood** [comment] 2023-02-01 18:34
Thanks @reesscot , it's working great for me (using Vite 3.2.3)!

And hopefully eventually we can get rid of the Vite workarounds mentioned in this issue:
https://github.com/aws-amplify/amplify-js/issues/9639

**Comment by reesscot** [comment] 2023-02-01 18:46
So glad to hear ESM in NodeJS is working for you @micah-redwood! We are also working on fixing the remaining vite issues as well, which can be tracked in the [ticket you linked](https://github.com/aws-amplify/amplify-js/issues/9639).
