### ISSUE TITLE
Signing out doesn't allow user to sign-in back

### ISSUE THREAD

**Issue by rrhalim** [aws-amplify/amplify-ui#1760] opened 2022-04-22 14:04 UTC
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Create React App

### Please describe your bug.

I need to set the `signOut` method to the context so I can call it from other pages.  
When I call `logout()`, it logs me out and shows the signin page.  When I try to sign in again, nothing happens.
I need to refresh the page so I can sign in again.

### What's the expected behaviour?

It should allow me to signin again after signing out.

### Help us reproduce the bug!

Please see code snippet.
Using "@aws-amplify/ui-react": "^2.15.2".

### Code Snippet

```typescript
import { withAuthenticator } from "@aws-amplify/ui-react";
import "@aws-amplify/ui-react/styles.css";

export const AmplifyContext = createContext<{logout: any}>({
  logout: undefined,
});

function MainPage({ signOut, user }) {
  const logout = signOut;
  return (
    <AmplifyContext.Provider value={{ logout }}>
      <AnotherComponent />
      <button onClick={signOut}>Sign out</button>
    </AmplifyContext.Provider>
 );
}
export default withAuthenticator(MainPage);
```

```typescript
const AnotherComponent: React.FC = () => {
  const { logout } = useContext(AmplifyContext);
  ...
  logout();
  ...
}
export default AnotherComponent;
```

**Comment by ErikCH** [comment] 2022-04-22 21:41
Hi @rrhalim !

The best way to share `logout` between multiple components is to use our [`useAuthenticator` hook](https://ui.docs.amplify.aws/components/authenticator#useauthenticator-hook) with `signOut`.

```
  const { signOut } = useAuthenticator((context) => [context.signOut]);
```

Just beware, if you'd like to use this in multiple routes, you'll need to surround the application in a [Authenticator.Provider](https://ui.docs.amplify.aws/getting-started/installation#authenticator-provider). Otherwise, `useAuthenticator` will not work.

Could you give that a try? And let me know if this solves your issue?

**Comment by rrhalim** [comment] 2022-04-29 11:22
I did as you instructed but the behavior is still the same.  Actually, upon login, I attach the `user.signInUserSession.accessToken.jwtToken` to the authorization header then I verify this token in the backend api by getting the cognito user using this access token.  If I don't get the user, then i send an invalid token reply.
The thing is, the access token seems to be the same both for when I initially login and for when i login again right after signing out.  Should they be different access tokens?

**Comment by ErikCH** [comment] 2022-05-11 20:40
Hi @rrhalim !

I did some more tests, and the `user.signInUserSession.accessToken.jwtToken` changes after every time I log out and log back in. The `origin_jti`, the `event_id` and the `jti` all change. You can use sites like `jwt.io` to look at the tokens and see what they look like.

I was unable to reproduce what you're seeing. Are you still having problems trying to sign in again? Do you see any network activity?

**Comment by ErikCH** [comment] 2022-05-12 18:09
Hi @rrhalim ! 

OK let me know if it happens again. I'll close this for now.

**Closed by ErikCH** 2022-05-12 18:09 UTC
Labels: bug, Authenticator, pending-response

**Comment by rrhalim** [comment] 2022-05-13 11:15
Now it's happening again.  I just added the following line and deployed again after signing out cannot sign in back

 Auth.currentAuthenticatedUser()
      .then(() => {
        navigate("/main");
      })
...
