### ISSUE TITLE
Support Email MFA

### ISSUE THREAD

**Issue by jjarvisp** [aws-amplify/amplify-ui#5983] opened 2024-10-30 23:39 UTC
### On which framework/platform would you like to see this feature implemented?

React, Angular, Vue, React Native

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

Recently, [Amazon Cognito has announced support for email as a multi-factor authentication option](https://aws.amazon.com/about-aws/whats-new/2024/09/amazon-cognito-user-pools-email-authentication-option/).

This feature request outlines enhancements to the Authenticator UI component to support this functionality.

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by esauerbo** [comment] 2024-10-31 13:39
Thanks for your feature request @jjarvisp, we will consider this in our roadmap planning.

**Comment by cwomack** [comment] 2024-11-05 17:36
Closing this as a duplicate of #5829 and will track progress for Email MFA within the Authenticator component there.

**Closed by cwomack** 2024-11-05 17:36 UTC
Labels: duplicate, feature-request, Authenticator
