### ISSUE TITLE
Autocomplete field is broken: it displays popup list under the another UI components

### ISSUE THREAD

**Issue by Alex-Github-Account** [aws-amplify/amplify-ui#2986] opened 2022-11-15 05:59 UTC
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Other

### How is your app built?

Create React App

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Please describe your bug.

Autocomplete field has popup-list that is not top layer on z-index, thus it gets covered by any element that has either higher z-index or css style 'position' set to 'sticky'. See the screenshot:
![amplify sucks](https://user-images.githubusercontent.com/60236507/201837374-0edff71d-4439-41cb-9346-6a8e1239d0fd.PNG)

### What's the expected behaviour?

Default HTML component do not demonstrate such behaviour and is always top-layer:
![default](https://user-images.githubusercontent.com/60236507/201838060-822c10b4-ca7d-400f-af77-f006792a74b1.PNG)

### Help us reproduce the bug!

Just try to use autocomplete component while some element with position:sticky overlays it

### Code Snippet

                [Autocomplete
                  label="Autocomplete"
                  options={[{"id":"apple","label":"apple"},{"id":"banana","label":"banana"},{"id":"cherry","label":"cherry"},{"id":"grape","label":"grape"},{"id":"kiwis","label":"kiwis"},{"id":"lemon","label":"lemon"},{"id":"mango","label":"mango"},{"id":"orange","label":"orange"},{"id":"strawberry","label":"strawberry"}]}
                  placeholder="Search here..." div style="postion:sticky;top:0;left:0;width:100%;height:100%">sample text for element that will cover autocomplete field loren ipsum dolor amplify is amateur lib dont have calendar tables or even autocomplete is broken [/div]

### Additional information and screenshots

Default HTML component works flawlessly:
<label for="favorite_team">Favorite Team:</label>
<input type="text" name="team" id="favorite_team" list="team_list">
<datalist id="team_list">
  <option>Detroit Lions</option>
  <option>Detroit Pistons</option>
  <option>Detroit Red Wings</option>
  <option>Detroit Tigers</option>
  
</datalist>

**Comment by Alex-Github-Account** [comment] 2022-11-18 08:47
It has another problem with intercepring user input after browser window been unfocused then focused again. Awful, this is not production ready component. Have anyone tested it before release? I wrote my own proper autocomplete component in a less than a hour instead of this...

**Comment by zchenwei** [comment] 2022-11-18 19:54
> blem with intercepring user input after bro

Hey @Alex-Github-Account , sorry to see that frustrating behavior. But can you provide some screenshots and info(like browser and version) about how to reproduce it. I do not see this behavior

**Comment by Alex-Github-Account** [comment] 2022-11-20 10:03
There is screenshot in my first post. I made another one but cant attach into reply, there is no add image button. I dont care much since your component messes up with user input on window been focused/unfocused, I've just abandoned trying to pull anything usefull from amplify UI. No calendar, no table, no rich text edit, and the autocomplete with bugs. It is a joke, not UI lib.

**Comment by zchenwei** [comment] 2022-11-20 18:57
@Alex-Github-Account, we've bumped the z-index and it should get reflected in our next release. What I am asking is that user input issue, but looks like you have open a new issue for that in #3030. Thanks for reporting and we will try to reproduce it on our end. Closing this one :)

**Closed by zchenwei** 2022-11-20 18:57 UTC
Labels: pending-response, React, Primitive
