### ISSUE TITLE
[Feedback] AuthPiece is no longer available in the newest @aws-amplify/ui-react

### ISSUE THREAD

**Issue by MichaelWalker-git** [aws-amplify/amplify-ui#3596] opened 2022-07-26 19:27 UTC
**Page**: [`/cli/usage/lambda-triggers`](https://docs.amplify.aws/cli/usage/lambda-triggers)

Specifically here:
https://docs.amplify.aws/cli/usage/lambda-triggers/#auth-templates

**Feedback**:

Is this complete override ability allowed in the newer version?

In the docs here (https://ui.docs.amplify.aws/react/connected-components/authenticator/customization), it seems like everything, but the main fields can be adjusted.

**Comment by reesscot** [comment] 2023-07-13 20:48
Closing as a duplicate of https://github.com/aws-amplify/amplify-ui/issues/2288

**Closed by reesscot** 2023-07-13 20:48 UTC
Labels: feature-request, Authenticator, React
