### ISSUE TITLE
How to get ChallengeParameters - Auth v6 ?

### ISSUE THREAD

**Issue by HanojHanu** [aws-amplify/amplify-ui#4862] opened 2023-12-19 10:24 UTC
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Create React App

### Please describe your bug.

![image](https://github.com/aws-amplify/amplify-ui/assets/53425981/eff1ea53-59df-4cb4-be05-223e86d7fb09)

### What's the expected behaviour?

![image](https://github.com/aws-amplify/amplify-ui/assets/53425981/0a2005ca-6f4a-4bb2-9455-fe0ea713b656)
![image](https://github.com/aws-amplify/amplify-ui/assets/53425981/e7a87e0b-b11e-40a1-b84a-75d884b1e6c7)

### Help us reproduce the bug!

...

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by esauerbo** [comment] 2024-01-03 16:38
Hi @HanojHanu, thanks for filing this issue. To clarify, are you asking how to retrieve the `ChallengeParameters` with v6 so you can write a custom `confirmSignIn` message showing the delivery destination and delivery method?

**Comment by HanojHanu** [comment] 2024-01-04 09:32
I guess this issue must be pointed out in 
https://github.com/aws-amplify/amplify-js/issues/12780

Not here in Amplify UI.

**Comment by calebpollman** [comment] 2024-01-04 17:08
> I guess this issue must be pointed out in [aws-amplify/amplify-js#12780](https://github.com/aws-amplify/amplify-js/issues/12780)
> 
> Not here in Amplify UI.

@HanojHanu Closing and marking this issue as a duplicate of https://github.com/aws-amplify/amplify-js/issues/12780

**Closed by calebpollman** 2024-01-04 17:08 UTC
Labels: duplicate, question, Authenticator
