### ISSUE TITLE
React -- setting totpIssuer / totpUser doesn't do anything

### ISSUE THREAD

**Issue by epicfaace** [aws-amplify/amplify-ui#3092] opened 2022-11-27 00:48 UTC
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

webpack

### Please describe your bug.

I set formFields as per documentation:

```
  const formFields = {
      confirmation_code: {
        totpIssuer: "issuer",
        totpUsername: "username"
      }
    }
  };
```

### What's the expected behaviour?

It should use these custom values when making the QR code.

### Help us reproduce the bug!

1. Use react / amplify and set the above form fields.
2. The bug is apparent.

### Additional information and screenshots

I wonder if this commit (https://github.com/aws-amplify/amplify-ui/commit/2e524dc9f73dc86e011614740ed6f9f400678872#diff-c585283990ae826e5a553a05d4b1abc495c11e7f1c1cfdf215f21c1dc198a36aL51) broke it. Also, please add tests to ensure this functionality doesn't regress in the future!

**Comment by ErikCH** [comment] 2022-11-29 21:21
Hi @epicfaace ! You should use `QR` not `confirmation_code`.

It would like like this.

```
const formFields = {
  setupTOTP: {
        QR: {
          totpIssuer: 'test issuer',
          totpUsername: 'amplify_qr_test_user',
        },
      },
  }

export default function App() {
  return (
    <Authenticator formFields={formFields}>
      {({ signOut }) => <button onClick={signOut}>Sign out</button>}
    </Authenticator>
  );
}
```

https://ui.docs.amplify.aws/react/connected-components/authenticator/customization#update-setup-totp-qr-issuer-and-username

Could you try that and see if that fixes your problem?

**Comment by ErikCH** [comment] 2022-11-29 21:22
You can only set the totpIssuer when you setup the TOTP.

**Comment by epicfaace** [comment] 2022-12-03 05:01
Sorry, my sample code had a typo. I was actually using `QR`, and still had the problem of it not showing up properly. Here's the exact code we're using!

https://github.com/cisagov/crossfeed/blob/92dd857d90a08e4fb81546d9e3a0a120236065cb/frontend/src/pages/AuthLogin/AuthLogin.tsx#L48-L54

**Comment by 0618** [comment] 2022-12-13 01:08
Thanks @epicfaace  for reporting this issue. I was able to reproduce it. We'll fix it.

**Comment by reesscot** [comment] 2022-12-16 20:42
This seems related to https://github.com/aws-amplify/amplify-ui/issues/2886

**Comment by ErikCH** [comment] 2022-12-22 21:33
Hi @epicfaace ! I pushed a fix for this, it should be in our next release!

**Comment by ErikCH** [comment] 2022-12-23 19:19
Hi @epicfaace ! This has been released. Please re-open this issue if you still have any problems.

**Closed by ErikCH** 2022-12-23 19:19 UTC
Labels: bug, Authenticator, React

**Comment by epicfaace** [comment] 2022-12-24 16:37
Thank you!

**Comment by oliverob** [comment] 2024-04-10 16:59
This issue seems to be back at least for me. I am triggering the TOTP by using
```
async  handleSignIn(username, password) {
    try {
      const user = await Auth.signIn(username, password)
        if (user.challengeName !== 'SOFTWARE_TOKEN_MFA' && process.env.REACT_APP_MFA == "1") {
          user.challengeName = 'MFA_SETUP';
        }

      return user
  
    } catch (error) {
      console.log(error);
    }
  }
```
and then setting my formfiedls as such:
```
export const formFields = {
  setupTotp: {
    QR: {
      totpIssuer: 'OptiSeat',
      totpUsername: 'Users',
    },
  },
}
```
The form fields seem to be ignored by the QR code that is generated, and it keeps having an account name of AWS Cognito
