### ISSUE TITLE
Package path ./dist/styles.css is not exported from package 

### ISSUE THREAD

**Issue by SilverLinings89** [aws-amplify/amplify-ui#2999] opened 2022-11-16 22:17 UTC
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Angular

### Which UI component?

Authenticator

### How is your app built?

pretty default angular 15 setup

### What browsers are you seeing the problem on?

Chrome

### Please describe your bug.

I have migrated my working angular 14 app to angular 15. I don't exactly know what causes the problem but it has never happened before the upgrade but is happening now - it might, however, also be related to the recent changes in this library.

When I try to build the application I get the following errors:
```
./node_modules/@angular-devkit/build-angular/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[6].rules[0].oneOf[0].use[1]!./node_modules/@angular-devkit/build-angular/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[6].rules[0].oneOf[0].use[2]!./node_modules/@aws-amplify/ui-angular/theme.css - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/node_modules/css-loader/dist/cjs.js):
Error: Package path ./dist/styles.css is not exported from package ###/node_modules/@aws-amplify/ui-angular/node_modules/@aws-amplify/ui (see exports field in ###/node_modules/@aws-amplify/ui-angular/node_modules/@aws-amplify/ui/package.json)

./src/styles.scss?ngGlobalStyle - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/@angular-devkit/build-angular/node_modules/css-loader/dist/cjs.js):
Error: Package path ./dist/styles.css is not exported from package ###/node_modules/@aws-amplify/ui-angular/node_modules/@aws-amplify/ui (see exports field in ###/node_modules/@aws-amplify/ui-angular/node_modules/@aws-amplify/ui/package.json)
```
I assume that the export statement in packages/ui/package.json line 12 is the mistake, because the name is "./styles.css" instead of "./dist/styles.css". I'm not sure if the export without dist is required, so my proposed solution is adding the line `".dist/styles.css": "./dist/styles.css", ` which for me fixes the problem. I will create a PR with this change.

### What's the expected behaviour?

Should build.

### Help us reproduce the bug!

I think it should be enough to simply use Amplify UI in the newly released angular 15.

**Comment by SilverLinings89** [comment] 2022-11-16 22:43
The proposed changes is included in the pr 3001: https://github.com/aws-amplify/amplify-ui/pull/3001

**Comment by wlee221** [comment] 2022-11-23 08:34
Hi @SilverLinings89, thanks for opening this issue! I reproduced the issue with Angular 15, and we will examine your PR shortly.

**Comment by wlee221** [comment] 2022-11-24 08:24
Quick update, we merged your PR, and this patch will be released next Tuesday. Thanks for your patience! We'll close this issue after release.

**Comment by sefatanam** [comment] 2022-11-24 18:01
@wlee221 thanks for your update, Today, I also reproduce this issue after updating my angular project. Used version is bellow,

 ```
"dependencies": {
    "@angular/animations": "^15.0.1",
    "@angular/cdk": "^15.0.0",
    "@angular/common": "^15.0.1",
    "@angular/compiler": "^15.0.1",
    "@angular/core": "^15.0.1",
    "@angular/forms": "^15.0.1",
    "@angular/material": "^15.0.0",
    "@angular/platform-browser": "^15.0.1",
    "@angular/platform-browser-dynamic": "^15.0.1",
    "@angular/router": "^15.0.1",
    "@aws-amplify/datastore": "3.12.0",
    "@aws-amplify/ui-angular": "^3.1.1",
    "aws-amplify": "^5.0.4",
    "memo-decorator": "^2.0.1",
    "rxjs": "~7.5.0",
    "tslib": "^2.3.0",
    "viewerjs": "1.10.5",
    "zone.js": "0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^15.0.1",
    "@angular-eslint/builder": "15.1.0",
    "@angular-eslint/eslint-plugin": "15.1.0",
    "@angular-eslint/eslint-plugin-template": "15.1.0",
    "@angular-eslint/schematics": "15.1.0",
    "@angular-eslint/template-parser": "15.1.0",
    "@angular/cli": "^15.0.1",
    "@angular/compiler-cli": "^15.0.1",
    "@angular/language-service": "^15.0.1",
    "@types/jasmine": "~3.10.0",
    "@types/node": "^12.11.1",
    "@typescript-eslint/eslint-plugin": "^5.43.0",
    "@typescript-eslint/parser": "^5.43.0",
    "eslint": "^8.28.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-prettier": "^4.0.0",
    "husky": "^7.0.4",
    "jasmine-core": "~4.0.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.1.0",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "lint-staged": "^12.4.1",
    "prettier": "^2.6.2",
    "typescript": "~4.8.4"
  },
```

And the error that I get includes `./dist/styles.css` is,

```
Error: node_modules/amazon-cognito-identity-js/index.d.ts:1:1 - error TS6200: Definitions of the following identifiers conflict with those in another file: ClientMetadata, AuthenticationDetails, CognitoUser, CognitoUserAttribute, CognitoUserPool, CognitoUserSession, CognitoAccessToken, CognitoIdToken, CognitoRefreshToken, CookieStorage, UserAgent, appendToCognitoUserAgent, WordArray

1 declare module 'amazon-cognito-identity-js' {
  ~~~~~~~

  node_modules/aws-amplify/node_modules/amazon-cognito-identity-js/index.d.ts:1:1
    1 declare module 'amazon-cognito-identity-js' {
      ~~~~~~~
    Conflicts are in this file.


Error: node_modules/aws-amplify/node_modules/amazon-cognito-identity-js/index.d.ts:1:1 - error TS6200: Definitions of the following identifiers conflict with those in another file: ClientMetadata, AuthenticationDetails, CognitoUser, CognitoUserAttribute, CognitoUserPool, CognitoUserSession, CognitoAccessToken, CognitoIdToken, CognitoRefreshToken, CookieStorage, UserAgent, appendToCognitoUserAgent, WordArray

1 declare module 'amazon-cognito-identity-js' {
  ~~~~~~~

  node_modules/amazon-cognito-identity-js/index.d.ts:1:1
    1 declare module 'amazon-cognito-identity-js' {
      ~~~~~~~
    Conflicts are in this file.


Error: node_modules/aws-amplify/node_modules/amazon-cognito-identity-js/index.d.ts:4:14 - error TS2649: Cannot augment module 'NodeCallback' with value exports because it resolves to a non-module entity.

4  export type NodeCallback<E, T> = (err?: E, result?: T) => void;
               ~~~~~~~~~~~~


Error: node_modules/aws-amplify/node_modules/amazon-cognito-identity-js/index.d.ts:27:3 - error TS2717: Subsequent property declarations must have the same type.  Property 'mfaRequired' must be of type '((challengeName: any, challengeParameters: any) => void) | undefined', but here has type '((challengeName: ChallengeName, challengeParameters: any) => void) | undefined'.

27   mfaRequired?: (
     ~~~~~~~~~~~

  node_modules/amazon-cognito-identity-js/index.d.ts:27:3
    27   mfaRequired?: (challengeName: any, challengeParameters: any) => void;
         ~~~~~~~~~~~
    'mfaRequired' was also declared here.


Error: node_modules/aws-amplify/node_modules/amazon-cognito-identity-js/index.d.ts:31:3 - error TS2717: Subsequent property declarations must have the same type.  Property 'totpRequired' must be of type '((challengeName: any, challengeParameters: any) => void) | undefined', but here has type '((challengeName: ChallengeName, challengeParameters: any) => void) | undefined'.

31   totpRequired?: (
     ~~~~~~~~~~~~

  node_modules/amazon-cognito-identity-js/index.d.ts:28:3
    28   totpRequired?: (challengeName: any, challengeParameters: any) => void;
         ~~~~~~~~~~~~
    'totpRequired' was also declared here.


Error: node_modules/aws-amplify/node_modules/amazon-cognito-identity-js/index.d.ts:36:3 - error TS2717: Subsequent property declarations must have the same type.  Property 'mfaSetup' must be of type '((challengeName: any, challengeParameters: any) => void) | undefined', but here has type '((challengeName: ChallengeName, challengeParameters: any) => void) | undefined'.

36   mfaSetup?: (challengeName: ChallengeName, challengeParameters: any) => void;
     ~~~~~~~~

  node_modules/amazon-cognito-identity-js/index.d.ts:30:3
    30   mfaSetup?: (challengeName: any, challengeParameters: any) => void;
         ~~~~~~~~
    'mfaSetup' was also declared here.


Error: node_modules/aws-amplify/node_modules/amazon-cognito-identity-js/index.d.ts:37:3 - error TS2717: Subsequent property declarations must have the same type.  Property 'selectMFAType' must be of type '((challengeName: any, challengeParameters: any) => void) | undefined', but here has type '((challengeName: ChallengeName, challengeParameters: any) => void) | undefined'.

37   selectMFAType?: (
     ~~~~~~~~~~~~~

  node_modules/amazon-cognito-identity-js/index.d.ts:31:3
    31   selectMFAType?: (challengeName: any, challengeParameters: any) => void;
         ~~~~~~~~~~~~~
    'selectMFAType' was also declared here.


Error: node_modules/type-fest/ts41/get.d.ts:93:37 - error TS2344: Type 'BaseType' does not satisfy the constraint 'Record<string | number, any>'.

93  : Key extends keyof WithStringKeys<BaseType>
                                       ~~~~~~~~

  node_modules/type-fest/ts41/get.d.ts:79:17
    79 type PropertyOf<BaseType, Key extends string> =
                       ~~~~~~~~
    This type parameter might need an `extends Record<string | number, any>` constraint.


Error: node_modules/type-fest/ts41/get.d.ts:94:19 - error TS2344: Type 'BaseType' does not satisfy the constraint 'Record<string | number, any>'.

94  ? WithStringKeys<BaseType>[Key]
                     ~~~~~~~~

  node_modules/type-fest/ts41/get.d.ts:79:17
    79 type PropertyOf<BaseType, Key extends string> =
                       ~~~~~~~~
    This type parameter might need an `extends Record<string | number, any>` constraint.
```

Hope that all those get resolved in the next release.

**Comment by wlee221** [comment] 2022-11-25 17:12
Hi @sefatanam, it looks like you have duplicate packages of `amazon-cognito-identity-js`. If you have upgraded from v2 to v3 recently, that might be why; can you try 

https://docs.amplify.aws/lib/troubleshooting/upgrading/q/platform/js/#upgrade-amplify-packages 

and see if this helps?

**Comment by sefatanam** [comment] 2022-11-27 15:36
Hi @wlee221,

Seems like there is no package duplications, then I followed these process:
- removed node_modules
- `npx npm-check-updates -i '/@?aws-amplify/' && npm update` runs this command, therefore it reduces the errors, now I'm getting this,

<font color="#E9AD0C"><b>(35:3) autoprefixer: end value has mixed support, consider using flex-end instead</b></font>

<font color="#A2734C">Warning: </font>/home/mds/Documents/MDS/uriself/node_modules/@aws-amplify/analytics/lib-esm/Providers/AmazonPersonalizeProvider.js depends on &apos;lodash/isEqual&apos;. CommonJS or AMD dependencies can cause optimization bailouts.
<font color="#E9AD0C"><b>For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies</b></font>

<font color="#A2734C">Warning: </font>/home/mds/Documents/MDS/uriself/node_modules/@aws-amplify/auth/lib-esm/Auth.js depends on &apos;url&apos;. CommonJS or AMD dependencies can cause optimization bailouts.
<font color="#E9AD0C"><b>For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies</b></font>

<font color="#A2734C">Warning: </font>/home/mds/Documents/MDS/uriself/node_modules/@aws-amplify/core/lib-esm/Signer.js depends on &apos;@aws-crypto/sha256-js&apos;. CommonJS or AMD dependencies can cause optimization bailouts.
<font color="#E9AD0C"><b>For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies</b></font>

<font color="#A2734C">Warning: </font>/home/mds/Documents/MDS/uriself/node_modules/@aws-amplify/datastore/lib-esm/util.js depends on &apos;buffer&apos;. CommonJS or AMD dependencies can cause optimization bailouts.
<font color="#E9AD0C"><b>For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies</b></font>

<font color="#A2734C">Warning: </font>/home/mds/Documents/MDS/uriself/node_modules/@aws-amplify/datastore/lib-esm/util.js depends on &apos;ulid&apos;. CommonJS or AMD dependencies can cause optimization bailouts.
<font color="#E9AD0C"><b>For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies</b></font>

<font color="#A2734C">Warning: </font>/home/mds/Documents/MDS/uriself/node_modules/@aws-amplify/datastore/lib-esm/util.js depends on &apos;uuid&apos;. CommonJS or AMD dependencies can cause optimization bailouts.
<font color="#E9AD0C"><b>For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies</b></font>

<font color="#A2734C">Warning: </font>/home/mds/Documents/MDS/uriself/node_modules/@aws-amplify/geo/lib-esm/Providers/AmazonLocationServiceProvider.js depends on &apos;camelcase-keys&apos;. CommonJS or AMD dependencies can cause optimization bailouts.
<font color="#E9AD0C"><b>For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies</b></font>

<font color="#A2734C">Warning: </font>/home/mds/Documents/MDS/uriself/node_modules/@aws-amplify/notifications/lib-esm/InAppMessaging/InAppMessaging.js depends on &apos;lodash/flatten&apos;. CommonJS or AMD dependencies can cause optimization bailouts.
<font color="#E9AD0C"><b>For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies</b></font>

<font color="#A2734C">Warning: </font>/home/mds/Documents/MDS/uriself/node_modules/@aws-amplify/notifications/lib-esm/InAppMessaging/SessionTracker/SessionTracker.js depends on &apos;lodash/noop&apos;. CommonJS or AMD dependencies can cause optimization bailouts.
<font color="#E9AD0C"><b>For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies</b></font>

<font color="#A2734C">Warning: </font>/home/mds/Documents/MDS/uriself/node_modules/@aws-amplify/notifications/node_modules/@aws-sdk/client-pinpoint/dist-es/runtimeConfig.browser.js depends on &apos;@aws-crypto/sha256-browser&apos;. CommonJS or AMD dependencies can cause optimization bailouts.
<font color="#E9AD0C"><b>For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies</b></font>

<font color="#A2734C">Warning: </font>/home/mds/Documents/MDS/uriself/node_modules/@aws-amplify/pubsub/lib-esm/Providers/MqttOverWSProvider.js depends on &apos;paho-mqtt&apos;. CommonJS or AMD dependencies can cause optimization bailouts.
<font color="#E9AD0C"><b>For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies</b></font>

<font color="#A2734C">Warning: </font>/home/mds/Documents/MDS/uriself/node_modules/@aws-amplify/ui-angular/fesm2015/aws-amplify-ui-angular.js depends on &apos;qrcode&apos;. CommonJS or AMD dependencies can cause optimization bailouts.
<font color="#E9AD0C"><b>For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies</b></font>

<font color="#A2734C">Warning: </font>/home/mds/Documents/MDS/uriself/node_modules/@aws-amplify/ui/dist/esm/helpers/authenticator/context.js depends on &apos;lodash/includes&apos;. CommonJS or AMD dependencies can cause optimization bailouts.
<font color="#E9AD0C"><b>For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies</b></font>

<font color="#A2734C">Warning: </font>/home/mds/Documents/MDS/uriself/node_modules/@aws-amplify/ui/dist/esm/helpers/authenticator/formFields/util.js depends on &apos;lodash/cloneDeep&apos;. CommonJS or AMD dependencies can cause optimization bailouts.
<font color="#E9AD0C"><b>For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies</b></font>

<font color="#A2734C">Warning: </font>/home/mds/Documents/MDS/uriself/node_modules/@aws-amplify/ui/dist/esm/helpers/authenticator/utils.js depends on &apos;xstate/lib/waitFor&apos;. CommonJS or AMD dependencies can cause optimization bailouts.
<font color="#E9AD0C"><b>For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies</b></font>

<font color="#A2734C">Warning: </font>/home/mds/Documents/MDS/uriself/node_modules/@aws-amplify/ui/dist/esm/machines/authenticator/index.js depends on &apos;xstate/lib/actions&apos;. CommonJS or AMD dependencies can cause optimization bailouts.
<font color="#E9AD0C"><b>For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies</b></font>

<font color="#A2734C">Warning: </font>/home/mds/Documents/MDS/uriself/node_modules/@aws-amplify/ui/dist/esm/theme/createTheme.js depends on &apos;style-dictionary/lib/utils/deepExtend&apos;. CommonJS or AMD dependencies can cause optimization bailouts.
<font color="#E9AD0C"><b>For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies</b></font>

<font color="#A2734C">Warning: </font>/home/mds/Documents/MDS/uriself/node_modules/@aws-amplify/ui/dist/esm/theme/createTheme.js depends on &apos;style-dictionary/lib/utils/flattenProperties&apos;. CommonJS or AMD dependencies can cause optimization bailouts.
<font color="#E9AD0C"><b>For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies</b></font>

<font color="#A2734C">Warning: </font>/home/mds/Documents/MDS/uriself/node_modules/@aws-amplify/ui/dist/esm/theme/utils.js depends on &apos;lodash/has&apos;. CommonJS or AMD dependencies can cause optimization bailouts.
<font color="#E9AD0C"><b>For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies</b></font>

<font color="#A2734C">Warning: </font>/home/mds/Documents/MDS/uriself/node_modules/@aws-amplify/ui/dist/esm/theme/utils.js depends on &apos;lodash/isObject&apos;. CommonJS or AMD dependencies can cause optimization bailouts.
<font color="#E9AD0C"><b>For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies</b></font>

<font color="#A2734C">Warning: </font>/home/mds/Documents/MDS/uriself/node_modules/@aws-amplify/ui/dist/esm/theme/utils.js depends on &apos;lodash/isString&apos;. CommonJS or AMD dependencies can cause optimization bailouts.
<font color="#E9AD0C"><b>For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies</b></font>

<font color="#A2734C">Warning: </font>/home/mds/Documents/MDS/uriself/node_modules/@aws-amplify/ui/dist/esm/theme/utils.js depends on &apos;lodash/kebabCase&apos;. CommonJS or AMD dependencies can cause optimization bailouts.
<font color="#E9AD0C"><b>For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies</b></font>

<font color="#A2734C">Warning: </font>/home/mds/Documents/MDS/uriself/node_modules/@aws-amplify/ui/dist/esm/theme/utils.js depends on &apos;style-dictionary/lib/utils/references/usesReference&apos;. CommonJS or AMD dependencies can cause optimization bailouts.
<font color="#E9AD0C"><b>For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies</b></font>

<font color="#A2734C">Warning: </font>/home/mds/Documents/MDS/uriself/node_modules/@aws-sdk/client-cognito-identity/dist/es/runtimeConfig.browser.js depends on &apos;@aws-crypto/sha256-browser&apos;. CommonJS or AMD dependencies can cause optimization bailouts.
<font color="#E9AD0C"><b>For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies</b></font>

<font color="#A2734C">Warning: </font>/home/mds/Documents/MDS/uriself/node_modules/@aws-sdk/client-lex-runtime-service/dist-es/runtimeConfig.browser.js depends on &apos;@aws-crypto/sha256-browser&apos;. CommonJS or AMD dependencies can cause optimization bailouts.
<font color="#E9AD0C"><b>For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies</b></font>

<font color="#A2734C">Warning: </font>/home/mds/Documents/MDS/uriself/node_modules/@aws-sdk/client-lex-runtime-v2/dist-es/runtimeConfig.browser.js depends on &apos;@aws-crypto/sha256-browser&apos;. CommonJS or AMD dependencies can cause optimization bailouts.
<font color="#E9AD0C"><b>For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies</b></font>

<font color="#A2734C">Warning: </font>/home/mds/Documents/MDS/uriself/node_modules/@aws-sdk/client-location/dist-es/runtimeConfig.browser.js depends on &apos;@aws-crypto/sha256-browser&apos;. CommonJS or AMD dependencies can cause optimization bailouts.
<font color="#E9AD0C"><b>For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies</b></font>

<font color="#A2734C">Warning: </font>/home/mds/Documents/MDS/uriself/node_modules/@aws-sdk/client-s3/dist/es/protocols/Aws_restXml.js depends on &apos;fast-xml-parser&apos;. CommonJS or AMD dependencies can cause optimization bailouts.
<font color="#E9AD0C"><b>For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies</b></font>

<font color="#A2734C">Warning: </font>/home/mds/Documents/MDS/uriself/node_modules/@aws-sdk/eventstream-codec/dist-es/EventStreamCodec.js depends on &apos;@aws-crypto/crc32&apos;. CommonJS or AMD dependencies can cause optimization bailouts.
<font color="#E9AD0C"><b>For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies</b></font>

<font color="#A2734C">Warning: </font>/home/mds/Documents/MDS/uriself/node_modules/@aws-sdk/eventstream-marshaller/dist/es/EventStreamMarshaller.js depends on &apos;@aws-crypto/crc32&apos;. CommonJS or AMD dependencies can cause optimization bailouts.
<font color="#E9AD0C"><b>For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies</b></font>

<font color="#A2734C">Warning: </font>/home/mds/Documents/MDS/uriself/node_modules/amazon-cognito-identity-js/es/Client.js depends on &apos;isomorphic-unfetch&apos;. CommonJS or AMD dependencies can cause optimization bailouts.
<font color="#E9AD0C"><b>For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies</b></font>

<font color="#A2734C">Warning: </font>/home/mds/Documents/MDS/uriself/node_modules/amazon-cognito-identity-js/es/CookieStorage.js depends on &apos;js-cookie&apos;. CommonJS or AMD dependencies can cause optimization bailouts.
<font color="#E9AD0C"><b>For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies</b></font>

<font color="#A2734C">Warning: </font>/home/mds/Documents/MDS/uriself/node_modules/universal-cookie/es6/Cookies.js depends on &apos;cookie&apos;. CommonJS or AMD dependencies can cause optimization bailouts.
<font color="#E9AD0C"><b>For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies</b></font>

<font color="#A2734C">Warning: </font>/home/mds/Documents/MDS/uriself/src/app/directives/img-zoom.directive.ts depends on &apos;viewerjs&apos;. CommonJS or AMD dependencies can cause optimization bailouts.
<font color="#E9AD0C"><b>For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies</b></font>

<font color="#A2734C">Warning: </font>/home/mds/Documents/MDS/uriself/src/app/pipes/get-name.pipe.ts depends on &apos;memo-decorator&apos;. CommonJS or AMD dependencies can cause optimization bailouts.
<font color="#E9AD0C"><b>For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies</b></font>



<font color="#2AA1B3">./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[5].rules[0].oneOf[0].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[5].rules[0].oneOf[0].use[2]!./node_modules/@aws-amplify/ui-angular/theme.css</font> - <font color="#F66151">Error: </font>Module build failed (from ./node_modules/css-loader/dist/cjs.js):
<font color="#F66151"><b>Error: Package path ./dist/styles.css is not exported from package /home/mds/Documents/MDS/uriself/node_modules/@aws-amplify/ui (see exports field in /home/mds/Documents/MDS/uriself/node_modules/@aws-amplify/ui/package.json)</b></font>

<font color="#2AA1B3">./src/styles/aws-amplify-ui.scss?ngGlobalStyle</font> - <font color="#F66151">Error: </font>Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
<font color="#F66151"><b>HookWebpackError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):</b></font>
<font color="#F66151"><b>Error: Package path ./dist/styles.css is not exported from package /home/mds/Documents/MDS/uriself/node_modules/@aws-amplify/ui (see exports field in /home/mds/Documents/MDS/uriself/node_modules/@aws-amplify/ui/package.json)</b></font>

<font color="#F66151">Error: </font><font color="#33C7DE">node_modules/type-fest/ts41/get.d.ts</font>:<font color="#E9AD0C">93</font>:<font color="#E9AD0C">37</font> - <font color="#F66151">error</font><font color="#5E5C64"> TS2344: </font>Type &apos;BaseType&apos; does not satisfy the constraint &apos;Record&lt;string | number, any&gt;&apos;.

<span style="background-color:#F66151"><font color="#002B36"><b>93</b></font></span>  : Key extends keyof WithStringKeys&lt;BaseType&gt;
<span style="background-color:#F66151"><font color="#002B36"><b>  </b></font></span> <font color="#F66151">                                    ~~~~~~~~</font>

<font color="#F66151"><b>  </b></font><font color="#33C7DE"><b>node_modules/type-fest/ts41/get.d.ts</b></font>:<font color="#E9AD0C">79</font>:<font color="#E9AD0C">17</font>
<font color="#F66151"><b>    </b></font><span style="background-color:#F66151"><font color="#002B36"><b>79</b></font></span> type PropertyOf&lt;BaseType, Key extends string&gt; =
<font color="#F66151"><b>    </b></font><span style="background-color:#F66151"><font color="#002B36"><b>  </b></font></span> <font color="#33C7DE">                ~~~~~~~~</font>
<font color="#F66151"><b>    This type parameter might need an `extends Record&lt;string | number, any&gt;` constraint.</b></font>


<font color="#F66151">Error: </font><font color="#33C7DE">node_modules/type-fest/ts41/get.d.ts</font>:<font color="#E9AD0C">94</font>:<font color="#E9AD0C">19</font> - <font color="#F66151">error</font><font color="#5E5C64"> TS2344: </font>Type &apos;BaseType&apos; does not satisfy the constraint &apos;Record&lt;string | number, any&gt;&apos;.

<span style="background-color:#F66151"><font color="#002B36"><b>94</b></font></span>  ? WithStringKeys&lt;BaseType&gt;[Key]
<span style="background-color:#F66151"><font color="#002B36"><b>  </b></font></span> <font color="#F66151">                  ~~~~~~~~</font>

<font color="#F66151"><b>  </b></font><font color="#33C7DE"><b>node_modules/type-fest/ts41/get.d.ts</b></font>:<font color="#E9AD0C">79</font>:<font color="#E9AD0C">17</font>
<font color="#F66151"><b>    </b></font><span style="background-color:#F66151"><font color="#002B36"><b>79</b></font></span> type PropertyOf&lt;BaseType, Key extends string&gt; =
<font color="#F66151"><b>    </b></font><span style="background-color:#F66151"><font color="#002B36"><b>  </b></font></span> <font color="#33C7DE">                ~~~~~~~~</font>
<font color="#F66151"><b>    This type parameter might need an `extends Record&lt;string | number, any&gt;` constraint.</b></font>
</pre>

**Comment by wlee221** [comment] 2022-11-27 17:46
Ooh, and that's the same error that @SilverLinings89 has fixed! This will be resolved once it is released (likely Tuesday, but I'll keep this thread updated).

**Comment by sefatanam** [comment] 2022-11-27 18:01
@wlee221 thanks you so much. eagerly waiting for it

**Comment by wlee221** [comment] 2022-12-01 00:18
The fix has been released now in `@aws-amplify/ui-angular@3.1.2`. Please let us know if problems still persist!

**Closed by wlee221** 2022-12-01 00:18 UTC
Labels: Angular, build

**Comment by sefatanam** [comment] 2022-12-10 10:28
Hi @wlee221 

after upgrading `@aws-amplify/ui-angular@3.1.2` to this version now getting this error & other package.json packages props remain same. Thanks


<pre><font color="#F66151">Error: </font><font color="#33C7DE">node_modules/type-fest/ts41/get.d.ts</font>:<font color="#E9AD0C">93</font>:<font color="#E9AD0C">37</font> - <font color="#F66151">error</font><font color="#5E5C64"> TS2344: </font>Type &apos;BaseType&apos; does not satisfy the constraint &apos;Record&lt;string | number, any&gt;&apos;.

<span style="background-color:#F66151"><font color="#002B36"><b>93</b></font></span>  : Key extends keyof WithStringKeys&lt;BaseType&gt;
<span style="background-color:#F66151"><font color="#002B36"><b>  </b></font></span> <font color="#F66151">                                    ~~~~~~~~</font>

<font color="#F66151"><b>  </b></font><font color="#33C7DE"><b>node_modules/type-fest/ts41/get.d.ts</b></font>:<font color="#E9AD0C">79</font>:<font color="#E9AD0C">17</font>
<font color="#F66151"><b>    </b></font><span style="background-color:#F66151"><font color="#002B36"><b>79</b></font></span> type PropertyOf&lt;BaseType, Key extends string&gt; =
<font color="#F66151"><b>    </b></font><span style="background-color:#F66151"><font color="#002B36"><b>  </b></font></span> <font color="#33C7DE">                ~~~~~~~~</font>
<font color="#F66151"><b>    This type parameter might need an `extends Record&lt;string | number, any&gt;` constraint.</b></font>


<font color="#F66151">Error: </font><font color="#33C7DE">node_modules/type-fest/ts41/get.d.ts</font>:<font color="#E9AD0C">94</font>:<font color="#E9AD0C">19</font> - <font color="#F66151">error</font><font color="#5E5C64"> TS2344: </font>Type &apos;BaseType&apos; does not satisfy the constraint &apos;Record&lt;string | number, any&gt;&apos;.

<span style="background-color:#F66151"><font color="#002B36"><b>94</b></font></span>  ? WithStringKeys&lt;BaseType&gt;[Key]
<span style="background-color:#F66151"><font color="#002B36"><b>  </b></font></span> <font color="#F66151">                  ~~~~~~~~</font>

<font color="#F66151"><b>  </b></font><font color="#33C7DE"><b>node_modules/type-fest/ts41/get.d.ts</b></font>:<font color="#E9AD0C">79</font>:<font color="#E9AD0C">17</font>
<font color="#F66151"><b>    </b></font><span style="background-color:#F66151"><font color="#002B36"><b>79</b></font></span> type PropertyOf&lt;BaseType, Key extends string&gt; =
<font color="#F66151"><b>    </b></font><span style="background-color:#F66151"><font color="#002B36"><b>  </b></font></span> <font color="#33C7DE">                ~~~~~~~~</font>
<font color="#F66151"><b>    This type parameter might need an `extends Record&lt;string | number, any&gt;` constraint.</b></font>


</pre>

**Comment by SilverLinings89** [comment] 2022-12-12 13:10
There is an underlying REALLY IMPORTANT issue here: Because of this bug, angular 15 only works with the package 3.x. In our project we are using the s3 image component, which was in the legacy module in amplify 2 but is removed in 3 WITHOUT replacement. As a consequence, if we upgrade to angular 15, we have to upgrade to ui-angular 3 (because v2 doesn't work with angular 15). but we can't because the image component is not available in 3.x and we depend on it.
