### ISSUE TITLE
Definition of the DialCode leads to strange behavior of the 'forceNewPassword' form

### ISSUE THREAD

**Issue by mariusprehn** [aws-amplify/amplify-ui#1726] opened 2022-04-20 10:43 UTC
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Amplify

### Please describe your bug.

We want users to use two-factor authentication. 

The registration process is as follows:
The user is registered by us, without phone number. When logging in for the first time, the user is asked to change his initial password, which he received by email. In the same form the user is asked for his phone number.

We have limited the selection of the "dialCode" to one value, as follows (code Snippet).

However, if the user is registered with a phone number, by defining the above code, the phone number input field still appears only the dialCode is no longer visible.

Once we remove (code Snippet) the phone number field will not be displayed anymore.

    "@aws-amplify/auth": "4.4.3",
    "@aws-amplify/core": "4.4.1",
    "@aws-amplify/ui-react": "2.10.3",
    "aws-amplify": "4.3.16",
    "react": "17.0.2",
    .
    .
    .

### What's the expected behaviour?

If the user in the userPool already has a phone number, the field for entering the phone number, will no longer appear despite the definition (code Snippet) of the "dialCode".

### Help us reproduce the bug!

- Define formFields
- create user in Cognito User Pool with phone number
- login with initial password
- the error can be seen on the forceNewPassword form

### Code Snippet

```typescript
// Put your code below this line.
  forceNewPassword: {
    password: {
      labelHidden: false,
      label:
        'Das Passwort muss eine Mischung von Buchstaben, Ziffern und Symbolen enthalten (min. 8 Zeichen).',
    },
    phone_number: {
      labelHidden: false,
      label: 'Bitte geben Sie Ihre Mobilfunknummer ein.',
      dialCodeList: ['+49'],
    },
  },
```

### Additional information and screenshots

![Bildschirmfoto_2022-04-19_um_13 46 41](https://user-images.githubusercontent.com/63093778/164213878-c3d9c0e9-99ed-4102-934d-8ffc128dab2a.png)

**Comment by ErikCH** [comment] 2022-04-20 17:32
Hi @mariusprehn !

I tried to reproduce the issue, and I'm unable to do so. Could you try updating your React version to the latest? And see if it still occurs?

```"@aws-amplify/ui-react": "2.15.4",```

**Comment by mariusprehn** [comment] 2022-04-26 06:52
@ErikCH, thanks for the quick reply, even with version 2.15.5 the problem exists.

**Comment by mariusprehn** [comment] 2022-04-28 10:32
Can I possibly help and supply information?

**Comment by ErikCH** [comment] 2022-05-10 22:51
Hi @mariusprehn ! I'm trying again, and I'm still not able to reproduce. 

<img width="542" alt="image" src="https://user-images.githubusercontent.com/65630/167737504-89d7b777-2299-42c2-ac4c-9a8841032222.png">


I'm not sure what's happening. Could you perhaps look in the console and take a look to see if you see any errors? Also can you post the whole `Authenticator` page, so I can take a look?

**Comment by ErikCH** [comment] 2022-05-10 22:53
Or maybe you could message me, and we can jump on a phone call real quick?

**Comment by ErikCH** [comment] 2022-05-17 15:48
Closing, please re-open if this issue occurs again

**Closed by ErikCH** 2022-05-17 15:48 UTC
Labels: bug, Authenticator, pending-response, not-reproducible
