### ISSUE TITLE
jest + @testing-library/react-native fails with Authenticator

### ISSUE THREAD

**Issue by PavelPolyakov** [aws-amplify/amplify-ui#4181] opened 2023-06-28 17:01 UTC
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React Native

### Which UI component?

Authenticator

### How is your app built?

expo

### Please describe your bug.

I want to have `expo` + `jest` + `ts` + `@testing-library/react-native` + `@aws-amplify/ui-react-native` to work together. 
Everything works, until we start using Authenticator. I consider this important, since `@testing-library/react-native` has high adoption.

### What's the expected behaviour?

Expected behaviour, that it's possible to have the setup where `render` from `@testing-library/react-native` works together with `Authenticator`.

### Help us reproduce the bug!

I prepared a repo where it is reproduced: https://github.com/PP-etc/aws-amplify-bug-reproduction . It's a minimal `expo` application + all of the mentioned above. As soon as I include the `Authenticator`, the flow breaks and can not be fixed.

**Comment by calebpollman** [comment] 2023-06-28 17:33
Hi @PavelPolyakov. Noticed your reproduction repo does not have a `test` command, can you please double check it?

**Comment by PavelPolyakov** [comment] 2023-06-28 18:11
hi @calebpollman , 

Thanks for the prompt response. I added the `test`, so you can run `npm test`. 
There is also a [README.md](https://github.com/PP-etc/aws-amplify-bug-reproduction) with the [broader context](https://github.com/PP-etc/aws-amplify-bug-reproduction#failing-run-with-authenticator).

What I run
```
npx jest src/__tests__/render-works.test.tsx
npx jest src/__tests__/render-fails.test.tsx
```

**Comment by calebpollman** [comment] 2023-06-28 22:36
Thanks for updating the example @PavelPolyakov. Believe the issue is with the provided `jest` configuration (unrelated to `@testing-library/react-native`), specifically with  the `transformIgnorePatterns` value. Was able to get `jest` running in the repro by updating _jest.config.js_ to:

```js
module.exports = {
  preset: "jest-expo",
  // add `@aws-amplify/ui-react-native`, `@aws-sdk/.*` and `uuid`
  transformIgnorePatterns: [
    "node_modules/(?!((jest-)?react-native|@aws-amplify/ui-react-native|@react-native(-community)?)|expo(nent)?|@expo(nent)?/.*|@expo-google-fonts/.*|aws-amplify|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|react-native-svg|@aws-amplify/ui-react-native|@aws-sdk/.*|uuid)",
  ],
  // add `setupFiles`
  setupFiles: ["<rootDir>/jest.setup.js"],
  setupFilesAfterEnv: ["@testing-library/jest-native/extend-expect"],
};
```

Along with the addition of `jest.setup.js`:

```
// required due to `aws-amplify`
global.navigator = {
  ClientDevice_Browser: jest.fn(Promise.resolve),
};
```

Additionally you may need to mock some 3rd party libs, when using your example added these [mocks](https://github.com/aws-amplify/amplify-ui/tree/main/packages/react-native/src/__mocks__) that are used in the Amplify UI code base.

As this is not an issue with `@aws-amplify/ui-react-native` going to close this issue. Hope the above information helps!

**Closed by calebpollman** 2023-06-28 22:36 UTC
Labels: pending-triage

**Comment by PavelPolyakov** [comment] 2023-06-29 06:50
Thank you @calebpollman , I've applied your suggestions and now it works fine: https://github.com/PP-etc/aws-amplify-bug-reproduction/commit/8215d9af8f0163b9e974c28d34642cf7461534b0 .

For those who will be interested in the resolution — I've updated the repository.
