### ISSUE TITLE
Geo: Marker "TypeError: Cannot destructure property 'map' of '(0 , import_react4.useContext)(...)' as it is null."

### ISSUE THREAD

**Issue by RyanFrench** [aws-amplify/amplify-ui#5309] opened 2024-06-12 16:27 UTC
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Geo (MapView/LocationSearch)

### How is your app built?

Vite

### What browsers are you seeing the problem on?

Chrome, Safari

### Which region are you seeing the problem in?

us-east-1

### Please describe your bug.

When trying to add Markers to a MapView I am getting the error "TypeError: Cannot destructure property 'map' of '(0 , import_react4.useContext)(...)' as it is null.". I found a [similar error](https://github.com/aws-amplify/amplify-ui/issues/2270) that mentioned not installing `react-map-gl` as a dependency, however, I don't have it in my package.json.

### What's the expected behaviour?

Being able to add a Marker to a MapView

### Help us reproduce the bug!

Dependencies:
```json
{
  "dependencies": {
      "@aws-amplify/ui-react": "^6.1.12",
      "@aws-amplify/ui-react-geo": "^2.0.16",
      "@cloudscape-design/components": "^3.0.657",
      "@cloudscape-design/global-styles": "^1.0.27",
      "aws-amplify": "^6.3.6",
      "eslint": "^8.57.0",
      "react": "^18.3.1",
      "react-dom": "^18.3.1",
      "react-router-dom": "^6.23.1"
    },
    "devDependencies": {
      "@types/react": "^18.3.3",
      "@types/react-dom": "^18.3.0",
      "@typescript-eslint/eslint-plugin": "^7.13.0",
      "@typescript-eslint/parser": "^7.13.0",
      "@vitejs/plugin-react-swc": "^3.7.0",
      "eslint-config-prettier": "^9.1.0",
      "eslint-plugin-prettier": "^5.1.3",
      "eslint-plugin-react-hooks": "^4.6.2",
      "eslint-plugin-react-refresh": "^0.4.7",
      "prettier": "^3.3.2",
      "typescript": "^5.4.5",
      "vite": "^5.2.13"
  }
}
```

### Code Snippet

```typescript
// Put your code below this line.

  const onLoad = async () => {
      const map = mapRef.current.getMap();
      map.on("dragend", handleMapDrag);
      map.on("zoomend", handleMapZoom);
      try {
          const downloadResult = await downloadData({
              path: "locations/clusters.json",
          }).result;
          const markers: LocationMarker[] = JSON.parse(await downloadResult.body.text());
          setLocationMarkers(markers.slice(0, 1));
      } catch (error) {
          console.log("Error : ", error);
      }
  };
  return (
      <CustomAppLayout navigation={<Navigation />}>
          <MapView
              ref={mapRef}
              onLoad={onLoad}
              initialViewState={{
                  latitude: 49,
                  longitude: -91,
                  zoom: 4,
              }}
          />
          {locationMarkers.map((location: LocationMarker, index: number) => (
              <Marker key={index} longitude={location.longitude} latitude={location.latitude} />
          ))}
      </CustomAppLayout>
  );
```

### Console log output

TypeError: Cannot destructure property 'map' of '(0 , import_react4.useContext)(...)' as it is null.
    at Marker (chunk-JPDU3WDZ.js?v=2fca8a04:909:11)
    at renderWithHooks (chunk-3GS3N7PG.js?v=2fca8a04:11568:26)
    at mountIndeterminateComponent (chunk-3GS3N7PG.js?v=2fca8a04:14946:21)
    at beginWork (chunk-3GS3N7PG.js?v=2fca8a04:15934:22)
    at HTMLUnknownElement.callCallback2 (chunk-3GS3N7PG.js?v=2fca8a04:3674:22)
    at Object.invokeGuardedCallbackDev (chunk-3GS3N7PG.js?v=2fca8a04:3699:24)
    at invokeGuardedCallback (chunk-3GS3N7PG.js?v=2fca8a04:3733:39)
    at beginWork$1 (chunk-3GS3N7PG.js?v=2fca8a04:19793:15)
    at performUnitOfWork (chunk-3GS3N7PG.js?v=2fca8a04:19226:20)
    at workLoopSync (chunk-3GS3N7PG.js?v=2fca8a04:19165:13)

### Additional information and screenshots

The MapView loads correctly and displays the map, but once the request to retrieve the location markers completes it throws the error.

**Comment by esauerbo** [comment] 2024-06-12 19:34
Hey @RyanFrench thanks for creating this issue. I tried reproducing with your same dependencies but a simpler version of the code, i.e.
```jsx
    <MapView>
      <Marker latitude={latitude} longitude={longitude} />
    </MapView>
```
and did not see that error. 

Can you try the above and see if you have the same issue?

**Comment by RyanFrench** [comment] 2024-06-13 10:05
Hi. I've tried the following and I'm still getting the same error.

```typescript
<CustomAppLayout navigation={<Navigation />}>
    <MapView
        ref={mapRef}
        onLoad={onLoad}
        initialViewState={{
            latitude: 49,
            longitude: -91,
            zoom: 4,
        }}
        />
            <Marker latitude={41.6870318498326} longitude={-73.89415414350857} />
</CustomAppLayout>

**Comment by esauerbo** [comment] 2024-06-13 14:14
@RyanFrench could you try with just
```
<MapView>
      <Marker latitude={41.6870318498326} longitude={-73.89415414350857}/>
    </MapView>
```
This may seem pedantic but it will help us isolate the root cause to have a really simplified reproduction. 

Also I saw you ticked the box but can you try once more deleting node modules and reinstalling? I'd also recommend double checking that the versions that have been installed are what you expect them to be. You can run `npm ls <package-name>` or just look through `node_modules` for each dep and check the package.json. Additionally, make sure that you don't have any stray `package.json` files in any parent folders of this project as that can lead to issues with dependencies.

**Comment by RyanFrench** [comment] 2024-06-13 14:26
Thank you, I've now figured out the issue.  I was opening the MapView tag with 
```typescript
<MapView />
```
and not closing it, so the Marker was being created outside of a MapView

**Comment by esauerbo** [comment] 2024-06-13 15:41
Glad you were able to get it working! Gonna close this out

**Closed by esauerbo** 2024-06-13 15:41 UTC
Labels: pending-response, not-reproducible, Geo
