### ISSUE TITLE
Customize Form Fields section

### ISSUE THREAD

**Issue by TuTomasz** [aws-amplify/amplify-ui#2124] opened 2022-06-16 15:48 UTC
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

Currently, there are header() and footer()  in the authentication UI that can customize the authenticator sections. Could there be a solution or additional sections such as body() where we can customize the section between the form input elements and the submit button to add links or additional information or change the position of forgot password?

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by calebpollman** [comment] 2023-09-26 18:11
Closing and marking as duplicate of https://github.com/aws-amplify/amplify-ui/issues/2288

**Closed by calebpollman** 2023-09-26 18:11 UTC
Labels: feature-request, Authenticator, React
