### ISSUE TITLE
Signup and sign-in item cusimization does not work with Amplify-authenticator vue's Authenticator

### ISSUE THREAD

**Issue by Masaki-G** [aws-amplify/amplify-ui#2699] opened 2022-10-06 14:25 UTC
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Vue

### Which UI component?

Authenticator

### How is your app built?

vue.js

### What browsers are you seeing the problem on?

Chrome

### Please describe your bug.

I did as described in the tutorial customization in the amplify dev center.
Below is the link to the article in question
https://ui.docs.amplify.aws/vue/connected-components/authenticator/customization#sign-up-field-order

I wrote the code as follows and it looks like the image

```vue
<script setup>
import { Authenticator } from "@aws-amplify/ui-vue";
import "@aws-amplify/ui-vue/styles.css";
import { I18n } from "aws-amplify";
import { translations } from "@aws-amplify/ui-vue";
I18n.putVocabularies(translations);
I18n.setLanguage("ja");
const formFields = {
    signUp: {
      email: {
        order:1
      },
      family_name: {
        order: 2
      },
      preferred_username: {
        order: 4
      },
      birthdate: {
        order: 3
      },
      password: {
        order: 5
      },
      confirm_password: {
        order: 6
      }
    },
}


</script>
<template>
  <authenticator :form-fields="formFields">

    <template v-slot="{ user, signOut }">
      <h1>Hello {{ user.username }}!</h1>
      <button @click="signOut">Sign Out</button>
    </template>
  </authenticator>
</template>

```
![image](https://user-images.githubusercontent.com/53896421/194337997-bb740f7c-9f14-4467-8df9-147dd3582524.png)

It is not the correct behavior that all added items are username

### What's the expected behaviour?

Be as shown in the official customization image.

![image](https://user-images.githubusercontent.com/53896421/194338310-f1dc2362-593d-475f-93b4-e0c998b2c63a.png)

### Help us reproduce the bug!

vue.js 3.0
node.js 14.10.0

In the above environment, follow the tutorial on the AMPLIFY dev center and follow the customization page to achieve the above.

**Comment by 0618** [comment] 2022-10-07 01:02
Thanks for reporting the issue. We had a fix for it https://github.com/aws-amplify/amplify-ui/pull/2697 Let me know if you still have the issue with the latest version 3.5.7.

**Comment by Masaki-G** [comment] 2022-10-07 05:18
Is it correct that the version of vue.js is 3.5.7.

**Comment by reesscot** [comment] 2022-10-10 17:23
This was not fixed in https://github.com/aws-amplify/amplify-ui/pull/2697, we will triage this issue.

**Comment by wlee221** [comment] 2022-10-10 23:12
I could reproduce this issue, thanks for your report. Working on a fix, and I'll keep you updated.

**Comment by wlee221** [comment] 2022-10-10 23:59
Hi @Masaki-G! One thing, our documentation was wrong with that code snippet. In addition to `formFields` override, you need to override `:sign-up-attributes` for them to align and formfields to render the right fields:

```diff
<script>
// ...
+ const signUpAttributes="['birthdate', 'family_name', 'preferred_username']";
</script>

<template>
- <authenticator :form-fields="formFields">
+ <authenticator :form-fields="formFields" :sign-up-attributes="signUpAttributes">

    <template v-slot="{ user, signOut }">
      <h1>Hello {{ user.username }}!</h1>
      <button @click="signOut">Sign Out</button>
    </template>
  </authenticator>
</template>
```

Let us know if that fixes your code on your end.

**Comment by wlee221** [comment] 2022-10-11 00:03
From our side, we'll have to fix two things:
- Fix our documentation (short term)
- Better default behavior if `sign-up-attributes` isn't provided (long term)

**Comment by Masaki-G** [comment] 2022-10-11 04:14
Hi wlee221
Would it be correct to override` :sign-up-attributes` for sign-up and `:sign-in-attributes` for sign-in?
Also, it says `const signUpAttributes="['birthdate', 'family_name', 'preferred_username']"; `do I need to do the same for form-fields?
I would like the entire code.

**Comment by wlee221** [comment] 2022-10-11 18:52
> Would it be correct to override :sign-up-attributes for sign-up and :sign-in-attributes for sign-in?

Just to learn your use case, why do you need to add additional attributes for sign-in? Usually attributes are only added to sign up because they're required to sign up.

**Comment by Masaki-G** [comment] 2022-10-12 06:43
Understood, thank you.

Looking forward to your update!

**Comment by ErikCH** [comment] 2022-12-15 19:19
Hi @Masaki-G ! Thanks for opening this up.

When updating the sign up page, the attributes listed are usually inferred from something we call [Zero Configuration](https://ui.docs.amplify.aws/react/connected-components/authenticator/configuration#sign-up-attributes). That will automatically detect the sign up attributes that are in the `aws-exports` file. I'll add a note to the sign up field order to make that more clear.

**Comment by ErikCH** [comment] 2022-12-22 21:33
Hi @Masaki-G ! I updated the documentation with more instructions so this does not happen. We'll look into a DX change in the future!

**Closed** 2023-01-28 01:24 UTC
Labels: bug, Documentation, feature-request, Authenticator
