### ISSUE TITLE
Undefined ('S3Object') Error

### ISSUE THREAD

**Issue by marcelcaferati** [aws-amplify/amplify-ui#5275] opened 2024-05-27 19:08 UTC
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Liveness

### How is your app built?

CRA

### What browsers are you seeing the problem on?

iOS , Android 

### Which region are you seeing the problem in?

sa-east-1

### Please describe your bug.

It happens at random times, after the user clicks "Start" on liveness check, it fails with the following error

{"state":"SERVER_ERROR","message":"Cannot read properties of undefined (reading 'S3Object')","name":"TypeError","sessionId":"dcd61f60-72d8-47fe-a1e6-9fbbef4350bd"}

these errors are really uncommon but are happening to us every now and then

### What's the expected behaviour?

Not to throw that error

### Help us reproduce the bug!

Not sure how to, I am not sure how it happens, but here is the session ID: dcd61f60-72d8-47fe-a1e6-9fbbef4350bd

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by thaddmt** [comment] 2024-05-28 22:03
Our component doesn't officially support react native so would be curious to see example code as that would really be our only way to help debug

**Comment by thaddmt** [comment] 2024-05-29 00:04
Understood, do you still have some sample code or anything that can help us in debugging?

Is it only happening with certain device and browser combinations?

**Comment by marcelcaferati** [comment] 2024-05-29 03:09
> Understood, do you still have some sample code or anything that can help us in debugging?
> 
> Is it only happening with certain device and browser combinations?

Sure, but i dont think I have much for you to go by, I really use the very basic setup form aws liveness tutorial, this is basically how I start the component and my backend is pretty much the very basic create session and get session in node, just like the tutorial

`<FaceLivenessDetector
                                    displayText={languages[i18n.language]}
                                    sessionId={sessionId}
                                    region={'us-east-1'}
                                    onAnalysisComplete={handleAnalysisComplete}
                                    onError={setLivenessError}
                                    components={{
                                        PhotosensitiveWarning: () => {
                                            return (
                                                <></>
                                            );
                                        }
                                    }}
                                />`

**Comment by thaddmt** [comment] 2024-05-29 04:58
Is it happening on any device or browser specifically? Anything that can help us try to reproduce?

**Comment by marcelcaferati** [comment] 2024-05-29 11:06
> Is it happening on any device or browser specifically? Anything that can help us try to reproduce?

I don't think I can provide an accurate way to reproduce it, it doesn't happen too often like the other error I reported, unfornutally we didn't have any users that sent us screen recording about this errors

**Comment by marcelcaferati** [comment] 2024-05-29 19:19
Sure!

our handleAnalysisComplete will call this call

```
const response = await get({
            apiName: "liveness",
            path: "/session/get", options: {
                queryParams: {
                    sessionId: sessionId,
                }
            }
        }).response
```

`app.get("/session/get", async function (req, res) {
    const rekognition = getRekognitionClient();
    const response = await rekognition.getFaceLivenessSessionResults({
        SessionId: req.query.sessionId,
    });
    res.status(200).json({response});
});`
Then our back end will perfom this operation to get the results

**Comment by thaddmt** [comment] 2024-05-30 21:02
Hm yeah I don't see any particular issue there, but from the error you posted above it looks like the client received an error while calling `onAnalysisComplete`. Are there any server logs that correspond with the session id you posted?

**Comment by thaddmt** [comment] 2024-05-31 00:12
Are you trying to parse out the S3Object from the audit image? That lines up with the shape of the response from getLivenessSession here - 

https://docs.aws.amazon.com/rekognition/latest/APIReference/API_GetFaceLivenessSessionResults.html#API_GetFaceLivenessSessionResults_ResponseSyntax

https://docs.aws.amazon.com/rekognition/latest/APIReference/API_AuditImage.html

**Comment by marcelcaferati** [comment] 2024-06-03 12:00
> Are you trying to parse out the S3Object from the audit image? That lines up with the shape of the response from getLivenessSession here -
> 
> https://docs.aws.amazon.com/rekognition/latest/APIReference/API_GetFaceLivenessSessionResults.html#API_GetFaceLivenessSessionResults_ResponseSyntax
> 
> https://docs.aws.amazon.com/rekognition/latest/APIReference/API_AuditImage.html

We are not trying to parse them no, but the error seems to be gone, without any aditional changes, I haven't gotten that error anymore

**Comment by thaddmt** [comment] 2024-06-03 20:47
Understood, closing this for now but please re-open if you feel like you find any other issues!

**Closed by thaddmt** 2024-06-03 20:47 UTC
Labels: question, being-investigated, Liveness
