### ISSUE TITLE
ui-react reset password TypeError: Cannot read properties of undefined (reading 'authAttributes')

### ISSUE THREAD

**Issue by ChrisChalke** [aws-amplify/amplify-ui#1436] opened 2022-03-01 17:51 UTC
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Create React App

### Please describe your bug.

I've just upgraded my React js app to use v2 of ui-react and now when I try the reset password process. I enter my email address and receive a code via email. When I enter the code and my new password (x2) and click submit the page hangs 
The error in the console is 
`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'authAttributes')
    at actorDoneData (bundle.js:54386:40)
    at bundle.js:154902:61
    at Array.reduce (<anonymous>)
    at updateContext (bundle.js:154884:48)
    at resolveActions (bundle.js:152205:103)
    at StateNode.resolveTransition (bundle.js:150875:131)
    at StateNode.transition (bundle.js:150811:17)
    at bundle.js:153216:28
    at provide (bundle.js:154099:16)
    at Interpreter.nextState (bundle.js:153215:78)`

I can see that the call to AWSCognitoIdentityProviderService.ConfirmForgotPassword is returning a 200 status code and the response is {} 

### What's the expected behaviour?

The page not to hang and it to allow me to continue with the log in process

### Help us reproduce the bug!

I can recreate it by using the out of the box app created by create-react-app:

1. npx create-react-app test-amplify --template typescript
2. cd test-amplify
3. npm install @aws-amplify/ui-react
4. In the generated App.tsx, surround the <header> with the <Authenticator> tag and add the cognito configuration. (See code snippet)
5. npm start 
6. Request a forgotten password code and then enter it with a new password - page hangs and error in console

Node version 16.14.0 
npm version 8.3.1
ui-react version: 2.6.2

### Code Snippet

```typescript
// Put your code below this line.
import logo from "./logo.svg";
import Amplify from "@aws-amplify/auth";
import "./App.css";
import { Authenticator } from "@aws-amplify/ui-react";
const coginitoConfiguration = {
  Auth: {
    region: "eu-west-2",
    userPoolId: process.env.REACT_APP_COGNITO_USER_POOL_ID,
    userPoolWebClientId: process.env.REACT_APP_COGNITO_APP_CLIENT_ID,
    mandatorySignIn: false,
    authenticationFlowType: "USER_PASSWORD_AUTH",
  },
};
Amplify.configure(coginitoConfiguration);
function App() {
  return (
    <div className="App">
      <Authenticator loginMechanisms={["email"]}>
        {({ signOut, user }) => (
          <header className="App-header">
            <img src={logo} className="App-logo" alt="logo" />
            <p>
              Edit <code>src/App.tsx</code> and save to reload.
            </p>
            <a className="App-link" href="https://reactjs.org" target="_blank" rel="noopener noreferrer">
              Learn React
            </a>
          </header>
        )}
      </Authenticator>
    </div>
  );
}
export default App;
```

**Comment by wlee221** [comment] 2022-03-01 18:47
Duplicate of https://github.com/aws-amplify/amplify-ui/issues/1414, closing. Fix has been merged and will be released this week.

**Comment by Milan-Shah** [comment] 2022-03-01 19:17
As @wlee221 mentioned, we will close this and follow [#1444](https://github.com/aws-amplify/amplify-ui/issues/1414)

**Closed by Milan-Shah** 2022-03-01 19:17 UTC
