### ISSUE TITLE
Custom SAML support for Authenticator component

### ISSUE THREAD

**Issue by isaac-rosterlab** [aws-amplify/amplify-ui#2020] opened 2022-06-02 02:35 UTC
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

I want to be able to log in to my app using Azure Active Directory and the Amplify UI custom authenticator component.

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by calebpollman** [comment] 2023-09-26 18:06
Marking as a duplicate of https://github.com/aws-amplify/amplify-ui/issues/1152 and closing

**Closed by calebpollman** 2023-09-26 18:06 UTC
Labels: feature-request, Authenticator
