### ISSUE TITLE
Error signing in with Authenticator component when @vue/compat is installed

### ISSUE THREAD

**Issue by dnewkerk** [aws-amplify/amplify-ui#4131] opened 2023-06-20 17:16 UTC
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Vue

### Which UI component?

Authenticator

### How is your app built?

Vite

### What browsers are you seeing the problem on?

Chrome, Firefox, Safari

### Please describe your bug.

I'm in the process of upgrading an app from Vue 2 to Vue 3, and we use the Authenticator component successfully in the Vue 2 app. Due to dependency requirements in our Vue 3 upgrade we currently use [@vue/compat](https://www.npmjs.com/package/@vue/compat)

After following the [Getting Started guide](https://docs.amplify.aws/start/q/integration/vue/) I found that when clicking the "Sign in" button I get a browser 404 error (full page reload, exits from Vue). The only thing in the dev tools console is this cryptic message: "VM10:5 crbug/1173575, non-JS module files deprecated."

For reference, our login flow with Authenticator includes a "Confirm SMS Code" step after clicking the "Sign in" button.

To investigate, I repeated the Amplify setup process on a clean Vue 3 install without @vue/compat and found that the error did not occur. I confirmed that the error returned simply by installing and enabling @vue/compat on the clean install. I tried various compatConfig options but didn't have any luck. I confirmed that I'm able to log in programmatically, so the problem is isolated to the Authenticator UI components.

I'm using the Vite config on:
https://v3-migration.vuejs.org/migration-build.html

### What's the expected behaviour?

Logging in without error.

### Help us reproduce the bug!

- Install the current version of Vue 3
- Add a component that implements the Authenticator component according to the Getting Started guide
- Install and enable https://www.npmjs.com/package/@vue/compat
- Attempt to log in, results in error

### Code Snippet

```typescript
<script lang="ts" setup>
import { Hub } from 'aws-amplify';
import { Authenticator } from '@aws-amplify/ui-vue';
import '@aws-amplify/ui-vue/styles.css';
</script>

<template>
  <authenticator>
    <template v-slot="{ user, signOut }">
      <h1>Hello {{ user.username }}!</h1>
      <button @click="signOut">Sign Out</button>
    </template>
  </authenticator>
</template>
```

**Comment by k4rl1** [comment] 2023-06-21 14:07
I have exactly the same issue.

**Comment by ErikCH** [comment] 2023-06-21 16:40
@dnewkerk and @k4rl1 What version of the `@aws-amplify/ui-vue` library are you running? When you were on Vue 2, then moved to Vue 3 did you upgrade your `ui-vue` library too?

**Comment by k4rl1** [comment] 2023-06-21 16:55
I used the latest version of @aws-amplify/ui-vue, actually I used the latest version of every library. I wanted to check this new amplify version with vue3 before fully migrate from our current codebase which uses vue 2 and the old amplify version.

**Comment by dnewkerk** [comment] 2023-06-21 17:52
@ErikCH thanks for the follow up! I tested using the latest version of Vue 3 and latest versions of `@aws-amplify/ui-vue` (was 3.1.18 as of yesterday I believe) and `aws-amplify` (5.3.0). So far as Vue 2 vs Vue 3, we did not have Amplify at all in our Vue 3 upgrade branch (it was added on the Vue 2 side while the Vue 3 upgrade has been in progress), so Amplify was installed from scratch on Vue 3 following the current Amplify Getting Started guide for Vue 3. Also I repeated and confirmed the test on a fresh install of Vue 3 to confirm it wasn't something going on in our own application code.

**Comment by reesscot** [comment] 2023-06-21 18:48
@dnewkerk @k4rl1 Do you know what you specifically need from the `@vue/compat` package? The `@aws-amplify/ui-vue` component only supports Vue 3. From reading the documentation it looks like this package turns on Vue 2 mode for the entire application: https://v3-migration.vuejs.org/migration-build.html#overview

This would probably explain why the `authenticator` component doesn't work with `@vue/compat` installed. I realize that it's not easy, but if you fully migrate the rest of your application to Vue 3 then there should be no problem using the new component. An alternative could be to use [per-component-config](https://v3-migration.vuejs.org/migration-build.html#per-component-config) to target the specific part of your application which uses the `authenticator`, but I'm not sure if that would work given you typically wrap the application in `authenticator`.

**Comment by dnewkerk** [comment] 2023-06-21 21:24
@reesscot in our case the only thing that has been forcing us to use `@vue/compat` for Vue 3 is [BootstrapVue](https://bootstrap-vue.org). They made an [initial Vue 3 release](https://bootstrap-vue.org/vue3) with the caveat that it relies on `@vue/compat`. As this is an extremely popular UI framework, I suspect this affects quite a few projects attempting to upgrade to Vue 3. Switching UI frameworks in our case is not an option. For those interested, there's a new alternative being developed called [BootstrapVueNext](https://github.com/bootstrap-vue-next/bootstrap-vue-next). This is what we're switching to as soon as possible.

As you mentioned, the Per-Component Config option is the solution for handling new or updated components in your app that use new Vue 3 features.... from the docs: "you can opt-in to Vue 3 behavior on a per-component basis with the [compatConfig option](https://v3-migration.vuejs.org/migration-build.html#per-component-config)".

Adding this line to the component opts it into full Vue 3 behavior (I'm not certain of the syntax if the component doesn't use the Options API):
`compatConfig: { MODE: 3 }`

The catch is this affects only the specific component, not child components nor third party components. So adding this to my parent `.vue` file which contains `<authenticator>` does not pass the setting down to authenticator. If there's a way do pass it into child/third party components I didn't find it.

I've come across some third party libraries which include the above compatConfig line in their components, and they work successfully in Vue 3 with `@vue/compat` installed. Also I had to fork and update an abandoned third party library, and adding this line to its components was the key to getting it working as well. Vue ignores the line if `@vue/compat` is not in use.

Would you be open to experimenting with adding the `compatConfig: { MODE: 3 }` line to the authenticator component (and any of its child components as needed)?

**Comment by zchenwei** [comment] 2023-06-21 23:28
Hey @dnewkerk, I am trying to experiment with the solution by adding `compatConfig: { MODE: 3 }` to authenticator component and its child components but it does not seem to get the app working. I could be doing something wrong with the plugin. Could you try to clone our repo and play around with it?

That being said, I do not think the team would agree on adding the line to our code base for supporting the migration build because the `@aws-amplify/ui-vue authenticator` component only supports Vue 3 by design and thus using any hacks to make it compatible with Vue 2 apps is not in consideration.

**Comment by reesscot** [comment] 2023-06-22 00:27
@dnewkerk We might be open to adding this flag since it's more of a flag that the component only support Vue 3 mode. However, I'm unsure whether it would actually help your use case since the components which use [BootstrapVue](https://bootstrap-vue.org/) would probably be inside of the <authenticator>. Would you mind putting a small demo repo together which demonstrates the issue including [BootstrapVue](https://bootstrap-vue.org/) that we could experiment with?

**Comment by dnewkerk** [comment] 2023-06-22 00:46
@zchenwei thanks for trying it out. Sure I'll clone and try on my end.

@reesscot sure, I'll try to put something together.

To clarify, `@vue/compat` is something you can only use in a Vue 3 app, and is integrated with Vue 3 itself.

Yes one of its purposes is to allow a Vue 3 app to run while it contains some deprecated Vue 2 code, namely so that a developer can note the deprecation warnings and manage the upgrade piece by piece. This isn't my use case right now (my application code is fully Vue 3) however for others I could imagine it might be helpful... for instance, if someone needed to get Authenticator working so they'd be able to log in and work on migrating their app to Vue 3. Right now they would get the error logging in and would be unable to login until their full app is 100% migrated to Vue 3, so they'd have to remove log in and leave it for last.

However the other use case is allowing a Vue 3 app to work while it has third party dependencies which haven't been "fully" updated to Vue 3 (which is my use case described above with BootstrapVue, where they made it compatible to install on Vue 3, but didn't rewrite/remove all deprecated code yet). In this case we're stuck between a third party dependency that's taking longer than expected to be fully upgraded, an oncoming EOL for Vue 2, lots of investment in getting an app upgraded to Vue 3, but no way to get Authenticator working. Quite a conundrum haha

Thanks!

**Comment by reesscot** [comment] 2023-10-10 23:37
@dnewkerk Is this something you are still interested in pursuing?

**Comment by reesscot** [comment] 2023-10-11 22:58
I'm closing this out since Vue 2 is not supported by the Amplify UI Authenticator and we don't have any plans to support the @vue/compat package at this time.

**Closed by reesscot** 2023-10-11 22:58 UTC
Labels: Vue, Authenticator, pending-response
